(function(){'use strict';
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let type='learningCourses', cache=[];
function pin(){return window.adminPin||localStorage.getItem('sandipani_admin_pin')||sessionStorage.getItem('sandipani_admin_pin')||''}
function setStatus(t,ok=true){const e=$('contentStatus');if(e){e.textContent=t;e.className='message '+(ok?'success':'error');}}
const configs={
 learningCourses:{title:'📚 Learning Hub Courses',fields:[['id','ID','text'],['class','Class','select:9th|10th|11th|12th'],['trade','Trade','select:IT-ITeS|Agriculture'],['medium','Medium','text'],['icon','Icon','text'],['level','Level','text'],['title','Course Title','text'],['description','Description','textarea'],['active','Active','select:Yes|No']],cols:['Class','Trade','Title','Level','Active']},
 learningLessons:{title:'📖 Learning Hub Lessons',fields:[['id','ID','text'],['courseId','Course ID','text'],['order','Order','number'],['code','Code','text'],['title','Lesson Title','text'],['content','Lesson Content','textarea'],['active','Active','select:Yes|No']],cols:['Course ID','Order','Title','Active']},
 practicalModules:{title:'🧪 Practical Lab Modules',fields:[['id','ID','text'],['module','Module Key','text'],['title','Title','text'],['description','Description','textarea'],['duration','Duration','text'],['instructions','Instructions','textarea'],['active','Active','select:Yes|No']],cols:['Module','Title','Duration','Active']},
 quizBank:{title:'📝 Central Quiz Question Bank',fields:[['id','ID','text'],['class','Class','select:9th|10th|11th|12th'],['trade','Trade','select:IT-ITeS|Agriculture'],['unit','Unit','text'],['mode','Mode','select:practice|timed'],['time','Time (sec)','number'],['question','Question','textarea'],['optionA','Option A','text'],['optionB','Option B','text'],['optionC','Option C','text'],['optionD','Option D','text'],['correct','Correct (0-3)','number'],['explanation','Explanation','textarea'],['active','Active','select:Yes|No']],cols:['Class','Trade','Unit','Question','Active']}
};
function renderForm(obj={}){const c=configs[type];$('contentForm').innerHTML=c.fields.map(([k,l,t])=>{let v=obj[k]??'';if(t.startsWith('select:'))return `<label>${esc(l)}<select data-field="${k}">${t.slice(7).split('|').map(x=>`<option ${String(v)===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label>`;return `<label>${esc(l)}${t==='textarea'?`<textarea data-field="${k}" rows="3">${esc(v)}</textarea>`:`<input data-field="${k}" type="${t==='number'?'number':'text'}" value="${esc(v)}">`}</label>`}).join('');$('contentEditId').value=obj.id||'';}
function readForm(){const o={};document.querySelectorAll('#contentForm [data-field]').forEach(e=>{o[e.dataset.field]=e.type==='number'?Number(e.value):e.value});o.id=$('contentEditId').value.trim()||o.id||'';return o;}
async function load(){try{const pinv=pin(); if(!pinv)throw new Error('Admin session not found.'); const action=type;cache=await API.call(action,{pin:pinv}); renderTable();renderForm();setStatus('Loaded '+cache.length+' records.',true);}catch(e){setStatus(e.message,false)}}
function renderTable(){const c=configs[type], head=c.cols.map(x=>`<th>${esc(x)}</th>`).join('');$('contentTableHead').innerHTML='<tr>'+head+'<th>Actions</th></tr>';$('contentTableBody').innerHTML=cache.map((r,i)=>`<tr>${c.cols.map(label=>{const key=Object.keys(r).find(k=>k.toLowerCase().replace(/[^a-z]/g,'')===label.toLowerCase().replace(/[^a-z]/g,''));return `<td>${esc(r[key]??'')}</td>`}).join('')}<td><button class="btn tiny" data-edit="${i}">Edit</button> <button class="btn danger tiny" data-delete="${esc(r.ID||r.id)}">Delete</button></td></tr>`).join('')||'<tr><td colspan="20">No records yet.</td></tr>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>renderForm(cache[Number(b.dataset.edit)]));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete));}
async function save(){try{const pinv=pin();if(!pinv)throw new Error('Admin session not found.');const data=readForm();if(type==='learningCourses'&&!data.title)throw new Error('Course title is required.');if(type==='learningLessons'&&(!data.courseId||!data.title))throw new Error('Course ID and lesson title are required.');if(type==='quizBank'&&(!data.question||!data.optionA||!data.optionB||!data.optionC||!data.optionD))throw new Error('Question and all 4 options are required.');await API.call('contentSave',{pin:pinv,type:type,data});setStatus('Saved to Google Sheet.',true);await load();}catch(e){setStatus(e.message,false)}}
async function remove(id){if(!confirm('Delete this content record?'))return;try{await API.call('contentDelete',{pin:pin(),type:type,id});setStatus('Deleted from Google Sheet.',true);await load();}catch(e){setStatus(e.message,false)}}
function select(t){type=t;document.querySelectorAll('[data-content-type]').forEach(b=>b.classList.toggle('active',b.dataset.contentType===t));$('contentTitle').textContent=configs[t].title;load();}
window.ContentAdmin={select,load,save,renderForm};
async function importBuiltIn(){try{const r=await fetch('content-seed.json');if(!r.ok)throw new Error('Seed file could not be loaded.');const seed=await r.json();const rows=seed[type]||[];if(!rows.length){setStatus('No built-in records for this section.',false);return;}if(!confirm('Import '+rows.length+' built-in records into Google Sheet? Existing IDs will be updated.'))return;for(const row of rows)await API.saveContent(pin(),type,row);setStatus('Imported '+rows.length+' built-in records into Google Sheet.',true);await load();}catch(e){setStatus(e.message,false)}}
window.addEventListener('DOMContentLoaded',()=>{const imp=$('contentImport');if(imp)imp.onclick=importBuiltIn;document.querySelectorAll('[data-content-type]').forEach(b=>b.onclick=()=>select(b.dataset.contentType));$('contentSave').onclick=save;$('contentNew').onclick=()=>renderForm();select(type);});
})();
