let adminPin='', records=[], settingsCache=[], configCache={};
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function msg(t,type='info'){const e=$('adminMessage');e.textContent=t;e.className='message '+type;e.style.display='block';}
async function adminLogin(){const pin=$('adminPin').value.trim();if(!pin)return msg('Enter Admin PIN.','error');try{const r=await API.createAdminSession(pin);if(!r||!r.token)return msg('Invalid Admin PIN.','error');adminPin=r.token;AdminAuth.set(r.token,r.expiresAt);$('loginCard').classList.add('hidden');$('connectionCard')?.classList.remove('hidden');$('adminPanel').classList.remove('hidden');$('apiUrl').value=localStorage.getItem('sandipani_api_url')||DEFAULT_API_URL;try{const c=await API.getConnectionInfo(pin);$('sheetRef').value=c.sheetUrl||'';}catch(e){}await refreshAll();msg('Admin login successful. One admin session now unlocks Gallery, Books, Notices, Staff, Documents, Learning Hub, Skills, Industry, Admission and all other admin modules for up to 5 hours or until you press Logout.','success');}catch(e){msg(e.message,'error');}}
function logout(){adminPin='';AdminAuth.clear();$('adminPanel').classList.add('hidden');$('connectionCard')?.classList.add('hidden');$('loginCard').classList.remove('hidden');}
function filters(){return { 'Academic Year':$('fYear').value,'Class':$('fClass').value,'Section':$('fSection').value,'Gender':$('fGender').value,'Stream':$('fStream').value,'IT Subject in Place of This Language':$('fIT').value,search:$('studentSearch').value.trim()};}
async function refreshAll(){await Promise.all([loadDashboard(),loadStudents(),loadSettings(),loadConfig(),loadGalleryAdmin()]);}
async function loadDashboard(){const s=await API.getStats(adminPin,filters());$('statStudents').textContent=s.total;$('c9').textContent=s.classes['9th'];$('c10').textContent=s.classes['10th'];$('c11').textContent=s.classes['11th'];$('c12').textContent=s.classes['12th'];$('gMale').textContent=s.gender.Male;$('gFemale').textContent=s.gender.Female;$('gOther').textContent=s.gender.Other;$('itHindi').textContent=s.it.Hindi;$('itEnglish').textContent=s.it.English;$('itBoth').textContent=s.it['Hindi & English'];$('aHindi').textContent=s.additional.Hindi;$('aEnglish').textContent=s.additional.English;$('aMath').textContent=s.additional.Mathematics;$('aBio').textContent=s.additional.Biology;$('aSkipHindi').textContent=s.additional['Completely Skipped Hindi'];$('aSkipEnglish').textContent=s.additional['Completely Skipped English'];$('sMath').textContent=s.stream.Mathematics;$('sBio').textContent=s.stream.Biology;$('sArts').textContent=s.stream.Arts;$('sCommerce').textContent=s.stream.Commerce;$('jDDEO').textContent=s.jobRole['Domestic Data Entry Operator'];$('jWeb').textContent=s.jobRole['Web Developer'];$('statDeleted').textContent=s.meta.deleted;$('statFields').textContent=s.meta.fields;}
async function loadStudents(){records=await API.getStudents(adminPin,filters());$('studentCount').textContent=records.length+' record(s)';$('studentRows').innerHTML=records.length?records.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r['Academic Year'])}</td><td>${esc(r.Class)}</td><td>${esc(r.Section)}</td><td>${esc(r['Roll Number']||'—')}</td><td>${esc(r['Student Name'])}</td><td>${esc(r["Father's Name"])}</td><td>${esc(r.Medium)}</td><td>${esc(r.Gender)}</td><td>${esc(r['Mobile Number'])}</td><td>${esc(r['Samagra ID'])}</td><td>${esc(r.Trade)}</td><td>${esc(r['Job Role'])}</td><td>${esc(r.Stream||'—')}</td><td>${esc(r['IT Subject in Place of This Language'])}</td><td>${esc(r['Additional Subject'])}</td><td><button class="mini" onclick="viewStudent(${r._row})">View</button> <button class="mini" onclick="editStudent(${r._row})">Edit</button> <button class="mini danger" onclick="deleteStudent(${r._row})">Delete</button></td></tr>`).join(''):'<tr><td colspan="17">No student records found.</td></tr>';}
function clearFilters(){['fYear','fClass','fSection','fGender','fStream','fIT','studentSearch'].forEach(id=>$(id).value='');applyFilters();}
async function applyFilters(){try{await Promise.all([loadStudents(),loadDashboard()]);}catch(e){msg(e.message,'error');}}
function optionsHtml(arr,selected=''){return (arr||[]).map(x=>`<option value="${esc(x)}" ${String(x)===String(selected)?'selected':''}>${esc(x)}</option>`).join('');}
function editForm(r){return `<div class="grid edit-grid"><div class="field"><label>Academic Year</label><select id="eYear">${optionsHtml(configCache.academicYears,r['Academic Year'])}</select></div><div class="field"><label>Class</label><select id="eClass"><option>9th</option><option>10th</option><option>11th</option><option>12th</option></select></div><div class="field"><label>Section</label><select id="eSection">${optionsHtml(configCache.sections,r.Section)}</select></div><div class="field"><label>Roll Number <small>(Admin will allot later)</small></label><input id="eRoll" inputmode="numeric" maxlength="6" value="${esc(r['Roll Number']||'')}"><div class="hint">Leave blank until roll number is allotted.</div></div><div class="field"><label>Student Name</label><input id="eName" value="${esc(r['Student Name'])}"></div><div class="field"><label>Father's Name</label><input id="eFather" value="${esc(r["Father's Name"])}"></div><div class="field"><label>Medium</label><select id="eMedium"><option ${r.Medium==='Hindi'?'selected':''}>Hindi</option><option ${r.Medium==='English'?'selected':''}>English</option></select></div><div class="field"><label>Gender</label><select id="eGender"><option>Male</option><option>Female</option><option>Other</option></select></div><div class="field"><label>Mobile Number</label><input id="eMobile" maxlength="10" value="${esc(r['Mobile Number'])}"></div><div class="field"><label>Samagra ID</label><input id="eSamagra" maxlength="9" value="${esc(r['Samagra ID'])}"></div><div class="field"><label>Trade</label><input value="IT-ITeS" readonly></div><div class="field"><label>Job Role</label><input id="eJob" readonly></div><div class="field" id="eStreamWrap"><label>Stream</label><select id="eStream"><option value="">Select Stream</option>${optionsHtml(['Mathematics','Biology','Arts','Commerce'],r.Stream)}</select></div><div class="field"><label>IT Subject in Place of This Language</label><select id="eIT">${optionsHtml(configCache.itReplacement,r['IT Subject in Place of This Language'])}</select></div><div class="field"><label>Additional Subject / Language Status</label><select id="eAdditional">${optionsHtml(configCache.additionalSubjects,r['Additional Subject'])}</select></div></div>`;}
function setEditClass(){const c=$('eClass').value;$('eJob').value=['9th','10th'].includes(c)?'Domestic Data Entry Operator':'Web Developer';$('eStreamWrap').style.display=['11th','12th'].includes(c)?'':'none';$('eStream').required=['11th','12th'].includes(c);}
function showAdminActionLoading(text='Please wait…'){
  let e=document.getElementById('adminActionLoading');
  if(!e){e=document.createElement('div');e.id='adminActionLoading';e.innerHTML='<div class="admin-action-loading-card"><div class="admin-action-spinner">⏳</div><h3 id="adminActionLoadingText"></h3><p>Please wait while the request is being processed.</p></div>';document.body.appendChild(e);}
  e.querySelector('#adminActionLoadingText').textContent=text;e.classList.add('show');
}
function hideAdminActionLoading(){document.getElementById('adminActionLoading')?.classList.remove('show');}
function modal(title,body,buttons=''){const old=$('modal');if(old)old.remove();document.body.insertAdjacentHTML('beforeend',`<div id="modal" class="modal"><div class="modal-card"><div class="modal-head"><h2>${title}</h2><button class="mini" onclick="closeModal()">✕</button></div><div>${body}</div>${buttons?`<div class="modal-actions">${buttons}</div>`:''}</div></div>`);}
function closeModal(){$('modal')?.remove();}
function findRow(row){return records.find(x=>Number(x._row)===Number(row));}
function viewStudent(row){const r=findRow(row);if(!r)return;const fields=['Academic Year','Class','Section','Roll Number','Student Name',"Father's Name",'Medium','Gender','Mobile Number','Samagra ID','Trade','Job Role','Stream','IT Subject in Place of This Language','Additional Subject'];modal('Student Details','<div class="detail-grid">'+fields.map(k=>`<div><small>${esc(k)}</small><b>${esc(r[k]||'—')}</b></div>`).join('')+'</div>','<button class="btn secondary" onclick="closeModal()">Close</button>');}
function editStudent(row){const r=findRow(row);if(!r)return;modal('Edit Student',editForm(r),'<button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveEdit('+row+')">Save Changes</button>');$('eClass').value=r.Class;$('eGender').value=r.Gender;$('eClass').addEventListener('change',setEditClass);setEditClass();}
async function saveEdit(row){const d={'Academic Year':$('eYear').value,Class:$('eClass').value,Section:$('eSection').value,'Roll Number':$('eRoll').value.trim(),'Student Name':$('eName').value.trim(),"Father's Name":$('eFather').value.trim(),Medium:$('eMedium').value,Gender:$('eGender').value,'Mobile Number':$('eMobile').value.trim(),'Samagra ID':$('eSamagra').value.trim(),Trade:'IT-ITeS','Job Role':$('eJob').value,Stream:['11th','12th'].includes($('eClass').value)?$('eStream').value:'','IT Subject in Place of This Language':$('eIT').value,'Additional Subject':$('eAdditional').value};try{await API.updateStudent(adminPin,row,d);closeModal();msg('Student updated successfully.','success');await applyFilters();}catch(e){msg(e.message,'error');}}
async function deleteStudent(row){const r=findRow(row);if(!r)return;if(!confirm(`Delete ${r['Student Name']}? This record will move to Deleted Records.`))return;try{await API.deleteStudent(adminPin,row);msg('Student deleted.','success');await applyFilters();await loadDeleted();}catch(e){msg(e.message,'error');}}
async function loadDeleted(){const d=await API.getDeleted(adminPin);$('deletedRows').innerHTML=d.length?d.map(x=>`<tr><td>${esc(x.deletedAt)}</td><td>${esc(x.type)}</td><td><button class="mini" onclick="restoreRecord(${x.row})">Restore</button></td></tr>`).join(''):'<tr><td colspan="3">No deleted records.</td></tr>';}
async function restoreRecord(row){if(!confirm('Restore this student record?'))return;try{await API.restoreDeleted(adminPin,row);msg('Record restored.','success');await refreshAll();await loadDeleted();}catch(e){msg(e.message,'error');}}
function csvEscape(v){return '"'+String(v??'').replace(/"/g,'""')+'"';}
function exportCSV(){const cols=['Academic Year','Class','Section','Roll Number','Student Name',"Father's Name",'Medium','Gender','Mobile Number','Samagra ID','Trade','Job Role','Stream','IT Subject in Place of This Language','Additional Subject'];const csv=[cols,...records.map(r=>cols.map(c=>r[c]||''))].map(row=>row.map(csvEscape).join(',')).join('\r\n');downloadBlob(csv,'vocational-student-records.csv','text/csv;charset=utf-8');}
function exportExcel(){const cols=['Sr. No.','Academic Year','Class','Section','Roll Number','Student Name',"Father's Name",'Medium','Gender','Mobile Number','Samagra ID','Trade','Job Role','Stream','IT Subject in Place of This Language','Additional Subject'];const rows=records.map((r,i)=>[i+1,...cols.slice(1).map(c=>r[c]||'')]);const html='<html><head><meta charset="UTF-8"></head><body><table border="1"><tr>'+cols.map(c=>`<th>${esc(c)}</th>`).join('')+'</tr>'+rows.map(row=>'<tr>'+row.map(c=>`<td>${esc(c)}</td>`).join('')+'</tr>').join('')+'</table></body></html>';downloadBlob(html,'vocational-student-records.xls','application/vnd.ms-excel');}
function downloadBlob(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function printReport(){const w=window.open('','_blank');w.document.write('<html><head><title>Vocational Student Report</title><style>body{font-family:Arial}table{border-collapse:collapse;width:100%;font-size:11px}th,td{border:1px solid #777;padding:5px}th{background:#eee}</style></head><body><h2>Vocational Student Record Report</h2><table><tr>'+['Sr. No.','Academic Year','Class','Section','Roll Number','Student Name',"Father's Name",'Medium','Gender','Mobile Number','Samagra ID','Trade','Job Role','Stream','IT Subject in Place of This Language','Additional Subject'].map(c=>`<th>${esc(c)}</th>`).join('')+'</tr>'+records.map((r,i)=>'<tr>'+[i+1,'Academic Year','Class','Section','Roll Number','Student Name',"Father's Name",'Medium','Gender','Mobile Number','Samagra ID','Trade','Job Role','Stream','IT Subject in Place of This Language','Additional Subject'].map((c,j)=>`<td>${esc(j===0?i+1:r[c]||'—')}</td>`).join('')+'</tr>').join('')+'</table><script>window.print();</script></body></html>');w.document.close();}
function fieldRow(f,i){return `<div class="builder-row" data-index="${i}"><input class="sf-name" value="${esc(f.field)}" ${f.system?'readonly':''}><select class="sf-type"><option value="text" ${f.type==='text'?'selected':''}>text</option><option value="dropdown" ${f.type==='dropdown'?'selected':''}>dropdown</option><option value="tel" ${f.type==='tel'?'selected':''}>tel</option><option value="number" ${f.type==='number'?'selected':''}>number</option></select><input class="sf-options" placeholder="Options separated by |" value="${esc(f.options)}"><select class="sf-required"><option value="Yes" ${f.required?'selected':''}>Required</option><option value="No" ${!f.required?'selected':''}>Optional</option></select><input class="sf-classes" placeholder="All or 9th|10th" value="${esc(f.onlyClasses||'All')}"><input class="sf-section" placeholder="Section" value="${esc(f.section||'Custom')}"><label><input class="sf-enabled" type="checkbox" ${f.enabled?'checked':''}> On</label><button class="mini danger" onclick="removeField(${i})">Delete</button></div>`;}
function renderBuilder(){$('builder').innerHTML=settingsCache.map(fieldRow).join('');}
async function loadSettings(){settingsCache=await API.getSettings();renderBuilder();}
async function loadConfig(){configCache=await API.getConfig();$('fYear').innerHTML='<option value="">All Academic Years</option>'+optionsHtml(configCache.academicYears);$('fSection').innerHTML='<option value="">All Sections</option>'+optionsHtml(configCache.sections);}
function addField(){settingsCache.push({field:'New Custom Field',type:'text',options:'',required:false,enabled:true,onlyClasses:'All',system:false,section:'Custom'});renderBuilder();}
function removeField(i){if(settingsCache[i].system)return alert('Core field cannot be deleted.');settingsCache.splice(i,1);renderBuilder();}
async function saveSettings(){const rows=[...document.querySelectorAll('.builder-row')];const next=rows.map((r,i)=>({...settingsCache[i],field:r.querySelector('.sf-name').value.trim(),type:r.querySelector('.sf-type').value,options:r.querySelector('.sf-options').value,required:r.querySelector('.sf-required').value==='Yes',onlyClasses:r.querySelector('.sf-classes').value||'All',section:r.querySelector('.sf-section').value||'Custom',enabled:r.querySelector('.sf-enabled').checked}));try{settingsCache=await API.saveSettings(adminPin,next);renderBuilder();msg('Form Builder saved.','success');}catch(e){msg(e.message,'error');}}
async function saveConfig(){const cfg={academicYears:$('cfgYears').value.split(/[,\n|]+/).map(x=>x.trim()).filter(Boolean),sections:$('cfgSections').value.split(/[,\n|]+/).map(x=>x.trim()).filter(Boolean),itReplacement:configCache.itReplacement,additionalSubjects:configCache.additionalSubjects};try{configCache=await API.saveConfig(adminPin,cfg);await loadConfig();msg('Academic years and sections saved.','success');}catch(e){msg(e.message,'error');}}
function showTab(tab){document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('hidden',x.id!=='panel-'+tab));if(tab==='deleted')loadDeleted();if(tab==='settings'){loadSettings();$('cfgYears').value=(configCache.academicYears||[]).join(', ');$('cfgSections').value=(configCache.sections||[]).join(', ');}if(tab==='skills'){loadSkillCenter();loadCertificatesCenter();}if(tab==='industry'){loadIndustryCenter();}if(tab==='admission'){loadAdmissionCenter();}}
function saveApiUrl(){const v=$('apiUrl').value.trim();if(!/^https:\/\/script\.google\.com\/macros\/s\//i.test(v))return msg('Please enter a valid Apps Script Web App URL.','error');localStorage.setItem('sandipani_api_url',v);msg('Script URL saved securely in this browser.','success');} 
async function connectSheet(){const ref=$('sheetRef').value.trim();if(!ref)return msg('Paste Google Sheet URL or ID first.','error');try{const d=await API.connectSheet(adminPin,ref);$('sheetRef').value=d.sheetUrl;msg('Google Sheet connection changed successfully.','success');}catch(e){msg(e.message,'error');}}
async function setupInfo(){try{const d=await API.call('setup');$('sheetRef').value=d.sheetUrl||'';msg('Current Google Sheet opened/initialized.','success');window.open(d.sheetUrl,'_blank');}catch(e){msg(e.message,'error');}}
document.addEventListener('DOMContentLoaded',async()=>{
  /* Never trust a legacy persistent token from older builds. */
  try{localStorage.removeItem('sandipani_admin_session');localStorage.removeItem('sandipani_admin_session_expiry');}catch(e){}
  $('adminPanel').classList.add('hidden');$('connectionCard')?.classList.add('hidden');$('loginCard').classList.remove('hidden');
  $('adminPin')?.addEventListener('keydown',e=>{if(e.key==='Enter')adminLogin();});
  $('apiUrl').value=localStorage.getItem('sandipani_api_url')||DEFAULT_API_URL;
  if(await AdminAuth.verify()){
    adminPin=AdminAuth.get();
    $('loginCard').classList.add('hidden');$('connectionCard')?.classList.remove('hidden');$('adminPanel').classList.remove('hidden');
    try{const c=await API.getConnectionInfo(adminPin);$('sheetRef').value=c.sheetUrl||'';}catch(e){}
    await refreshAll();
  }
});
window.addEventListener('pagehide',()=>{AdminAuth.clear();adminPin='';});
window.addEventListener('pageshow',async()=>{
  if(!AdminAuth.isUnlocked()){
    $('adminPanel')?.classList.add('hidden');
    $('connectionCard')?.classList.add('hidden');
    $('loginCard')?.classList.remove('hidden');
  }
});

async function loadGalleryAdmin(){
  const rows=await API.getGallery();
  const labels={guest:'Guest Lectures',industrial:'Industrial Visit',classroom:'Class Room Teaching',activities:'Student Activities'};
  const box=$('galleryAdminRows'); if(!box)return;
  box.innerHTML=(rows||[]).map(x=>{const section=x.section??x.Section??'';const title=x.title??x.Title??'';const url=x.thumbnailUrl??x['Image URL']??x.url??'';const id=x.id??x.ID??'';return `<tr><td>${esc(labels[section]||section)}</td><td>${esc(title)}</td><td>${url?`<img src="${esc(url)}" style="width:90px;height:60px;object-fit:cover;border-radius:8px">`:'—'}</td><td><button class="mini danger" onclick="deleteGalleryPhoto('${esc(id)}')">Delete</button></td></tr>`;}).join('')||'<tr><td colspan="4">No uploaded photos yet.</td></tr>';
}
async function uploadGalleryPhoto(){
  const file=$('galleryFile')?.files?.[0], section=$('gallerySection')?.value, title=$('galleryTitle')?.value.trim(), status=$('galleryUploadStatus');
  if(!file)return msg('Select a photo first.','error');
  if(!title)return msg('Enter a photo title.','error');
  if(!['image/jpeg','image/png','image/webp'].includes(file.type))return msg('Only JPG, PNG or WebP images are allowed.','error');
  status.textContent='Preparing photo…';status.className='message';status.style.display='block';
  try{
    const prepared=await prepareGalleryImage_(file);
    await API.uploadGallery(adminPin || (window.AdminAuth&&AdminAuth.get()) || '',{section,title,name:prepared.name,mimeType:prepared.mimeType,base64:prepared.base64});
    status.textContent='Photo uploaded successfully.';status.className='message success';
    $('galleryFile').value='';$('galleryTitle').value='';await loadGalleryAdmin();
  }catch(e){status.textContent=e.message||'Photo upload failed.';status.className='message error';}
}
function prepareGalleryImage_(file){
  return new Promise((resolve,reject)=>{
    const img=new Image(), url=URL.createObjectURL(file);
    img.onload=()=>{
      try{
        const maxSide=1800, scale=Math.min(1,maxSide/Math.max(img.naturalWidth,img.naturalHeight));
        const w=Math.max(1,Math.round(img.naturalWidth*scale)), h=Math.max(1,Math.round(img.naturalHeight*scale));
        const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;
        canvas.getContext('2d').drawImage(img,0,0,w,h);
        const make=q=>{
          const dataUrl=canvas.toDataURL('image/jpeg',q), b64=dataUrl.split(',')[1]||'';
          if(b64.length<=2200000 || q<=0.55){
            URL.revokeObjectURL(url);
            resolve({name:(file.name.replace(/\.[^.]+$/,'')||'gallery')+'.jpg',mimeType:'image/jpeg',base64:b64});
          }else make(q-0.08);
        };
        make(0.82);
      }catch(err){URL.revokeObjectURL(url);reject(err);}
    };
    img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Could not read the selected image.'));};
    img.src=url;
  });
}
async function deleteGalleryPhoto(id){if(!confirm('Delete this gallery photo?'))return;try{await API.deleteGallery(adminPin || (window.AdminAuth&&AdminAuth.get()) || '',id);msg('Gallery photo deleted.','success');await loadGalleryAdmin();}catch(e){msg(e.message,'error');}}

// Admin Automation Center: all bundled automation tools open inside the authenticated panel.
function openAutomation(title,key){const map={
'Guest Lecture Application':'automationGuestApplication','Guest Lecture Automatic System':'automationGuestAutomatic','Guest Lecture Report & Attendance':'automationGuestReport','Industry Visit Report Management':'automationIndustryReport','Marks Automation System':'automationMarks'};AdminCentral.open(map[title]||key);}

// ---------------- INDUSTRY CONNECT ----------------
async function loadIndustryCenter(){try{const d=await API.getIndustryDashboard(adminPin);['partners','activities','guestAttendance','visitAttendance','internships','verifiedInternships'].forEach(k=>{const el=$('ic'+({partners:'Partners',activities:'Activities',guestAttendance:'GuestAtt',visitAttendance:'VisitAtt',internships:'Internships',verifiedInternships:'Verified'}[k]));if(el)el.textContent=d[k]||0;});const q=$('industrySearch')?.value.trim()||'';const [acts,ins,ps]=await Promise.all([API.getIndustryActivities(adminPin,{search:q}),API.getInternships(adminPin,{search:q}),API.getIndustryPartners(adminPin,{search:q})]);$('industryActivityRows').innerHTML=(acts||[]).map(x=>`<tr><td>${esc(x['Activity Type'])}</td><td>${esc(x.Title)}</td><td>${esc(x.Class)}</td><td>${esc(x.Trade)}</td><td>${esc(x.Date)}</td><td>${esc(x['Partner/Guest'])}</td><td>${esc(x.Status)}</td><td><button class="mini" onclick='editIndustryActivity(${JSON.stringify(x).replace(/</g,'\\u003c')})'>Edit</button> <button class="mini" onclick='openAttendance("${esc(x['Activity ID'])}","${esc(x['Activity Type'])}")'>Attendance</button> <button class="mini danger" onclick='deleteIndustryActivity("${esc(x['Activity ID'])}")'>Delete</button></td></tr>`).join('')||'<tr><td colspan="8">No activities yet.</td></tr>';$('internshipRows').innerHTML=(ins||[]).map(x=>`<tr><td>${esc(x['Student Name'])}</td><td>${esc(x.Class)}</td><td>${esc(x['Roll Number'])}</td><td>${esc(x.Organization)}</td><td>${esc(x.Role)}</td><td>${esc(x['Start Date'])} → ${esc(x['End Date'])}</td><td>${esc(x.Status)}</td><td>${String(x.Verified).toLowerCase()==='yes'?'✅':'⏳'}</td><td><button class="mini" onclick='editInternship(${JSON.stringify(x).replace(/</g,'\\u003c')})'>Edit</button> <button class="mini danger" onclick='deleteInternship("${esc(x['Internship ID'])}")'>Delete</button></td></tr>`).join('')||'<tr><td colspan="9">No internships yet.</td></tr>';$('partnerRows').innerHTML=(ps||[]).map(x=>`<tr><td>${esc(x.Organization)}</td><td>${esc(x.Type)}</td><td>${esc(x['Contact Person'])}</td><td>${esc(x.Location)}</td><td>${esc(x['Industry/Domain'])}</td><td>${esc(x.Status)}</td><td><button class="mini" onclick='editPartner(${JSON.stringify(x).replace(/</g,'\\u003c')})'>Edit</button> <button class="mini danger" onclick='deletePartner("${esc(x['Partner ID'])}")'>Delete</button></td></tr>`).join('')||'<tr><td colspan="7">No industry partners yet.</td></tr>';}catch(e){msg(e.message,'error');}}
function openPartnerForm(x={}){modal('Industry Partner',`<div class="grid"><div class="field"><label>Organization</label><input id="ipOrg" value="${esc(x.Organization||'')}"></div><div class="field"><label>Type</label><input id="ipType" value="${esc(x.Type||'Company / Industry')}"></div><div class="field"><label>Contact Person</label><input id="ipContact" value="${esc(x['Contact Person']||'')}"></div><div class="field"><label>Phone</label><input id="ipPhone" value="${esc(x.Phone||'')}"></div><div class="field"><label>Email</label><input id="ipEmail" value="${esc(x.Email||'')}"></div><div class="field"><label>Location</label><input id="ipLocation" value="${esc(x.Location||'')}"></div><div class="field"><label>Industry / Domain</label><input id="ipDomain" value="${esc(x['Industry/Domain']||'')}"></div><div class="field"><label>Status</label><select id="ipStatus"><option>Active</option><option>Inactive</option></select></div><div class="field"><label>Notes</label><input id="ipNotes" value="${esc(x.Notes||'')}"></div></div><input type="hidden" id="ipId" value="${esc(x['Partner ID']||'')}">`,'<button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="savePartner()">Save</button>');}
async function savePartner(){try{await API.saveIndustryPartner(adminPin,{id:$('ipId').value,organization:$('ipOrg').value,partnerType:$('ipType').value,contactPerson:$('ipContact').value,phone:$('ipPhone').value,email:$('ipEmail').value,location:$('ipLocation').value,domain:$('ipDomain').value,status:$('ipStatus').value,notes:$('ipNotes').value});closeModal();loadIndustryCenter();}catch(e){msg(e.message,'error');}} function editPartner(x){openPartnerForm(x)} async function deletePartner(id){if(confirm('Delete partner?')){await API.deleteIndustryPartner(adminPin,id);loadIndustryCenter();}}
function openIndustryActivityForm(x={}){modal('Industry Connect Activity',`<div class="grid"><div class="field"><label>Activity Type</label><select id="iaType"><option>Guest Lecture</option><option>Industrial Visit</option></select></div><div class="field"><label>Title / Topic</label><input id="iaTitle" value="${esc(x.Title||'')}"></div><div class="field"><label>Academic Year</label><input id="iaYear" value="${esc(x['Academic Year']||'2026-27')}"></div><div class="field"><label>Class</label><select id="iaClass"><option>9th</option><option>10th</option><option>11th</option><option>12th</option></select></div><div class="field"><label>Trade</label><input id="iaTrade" value="${esc(x.Trade||'IT-ITeS')}"></div><div class="field"><label>Date</label><input id="iaDate" type="date" value="${esc(x.Date||'')}"></div><div class="field"><label>Partner ID / Guest</label><input id="iaPartner" value="${esc(x['Partner/Guest']||'')}"></div><div class="field"><label>Topic / Role</label><input id="iaTopic" value="${esc(x['Topic/Role']||'')}"></div><div class="field"><label>Duration</label><input id="iaDuration" value="${esc(x.Duration||'')}"></div><div class="field"><label>Objective</label><textarea id="iaObjective">${esc(x.Objective||'')}</textarea></div><div class="field"><label>Learning Outcomes</label><textarea id="iaOutcome">${esc(x['Learning Outcomes']||'')}</textarea></div><div class="field"><label>Status</label><select id="iaStatus"><option>Planned</option><option>Completed</option><option>Cancelled</option></select></div><div class="field"><label>Evidence URL</label><input id="iaEvidence" value="${esc(x['Evidence URL']||'')}"></div><div class="field"><label>Notes</label><input id="iaNotes" value="${esc(x.Notes||'')}"></div></div><input type="hidden" id="iaId" value="${esc(x['Activity ID']||'')}">`,'<button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveIndustryActivity()">Save Activity</button>');}
async function saveIndustryActivity(){try{await API.saveIndustryActivity(adminPin,{id:$('iaId').value,activityType:$('iaType').value,title:$('iaTitle').value,academicYear:$('iaYear').value,class:$('iaClass').value,trade:$('iaTrade').value,date:$('iaDate').value,partnerGuest:$('iaPartner').value,topicRole:$('iaTopic').value,duration:$('iaDuration').value,objective:$('iaObjective').value,learningOutcomes:$('iaOutcome').value,status:$('iaStatus').value,evidenceUrl:$('iaEvidence').value,notes:$('iaNotes').value});closeModal();loadIndustryCenter();}catch(e){msg(e.message,'error');}} function editIndustryActivity(x){openIndustryActivityForm(x)} async function deleteIndustryActivity(id){if(confirm('Delete activity?')){await API.deleteIndustryActivity(adminPin,id);loadIndustryCenter();}}
function openInternshipForm(x={}){modal('Internship Tracker',`<div class="grid"><div class="field"><label>Academic Year</label><input id="inYear" value="${esc(x['Academic Year']||'2026-27')}"></div><div class="field"><label>Class</label><select id="inClass"><option>9th</option><option>10th</option><option>11th</option><option>12th</option></select></div><div class="field"><label>Roll Number</label><input id="inRoll" value="${esc(x['Roll Number']||'')}"></div><div class="field"><label>Student Name</label><input id="inName" value="${esc(x['Student Name']||'')}"></div><div class="field"><label>Trade</label><input id="inTrade" value="${esc(x.Trade||'IT-ITeS')}"></div><div class="field"><label>Organization</label><input id="inOrg" value="${esc(x.Organization||'')}"></div><div class="field"><label>Role</label><input id="inRole" value="${esc(x.Role||'')}"></div><div class="field"><label>Mentor</label><input id="inMentor" value="${esc(x.Mentor||'')}"></div><div class="field"><label>Start</label><input id="inStart" type="date" value="${esc(x['Start Date']||'')}"></div><div class="field"><label>End</label><input id="inEnd" type="date" value="${esc(x['End Date']||'')}"></div><div class="field"><label>Duration</label><input id="inDuration" value="${esc(x.Duration||'')}"></div><div class="field"><label>Status</label><select id="inStatus"><option>Applied</option><option>Ongoing</option><option>Completed</option><option>Cancelled</option></select></div><div class="field"><label>Skills Learned</label><textarea id="inSkills">${esc(x['Skills Learned']||'')}</textarea></div><div class="field"><label>Certificate ID</label><input id="inCert" value="${esc(x['Certificate ID']||'')}"></div><div class="field"><label>Evidence URL</label><input id="inEvidence" value="${esc(x['Evidence URL']||'')}"></div><label><input id="inVerified" type="checkbox" ${String(x.Verified).toLowerCase()==='yes'?'checked':''}> Verified</label><div class="field"><label>Notes</label><input id="inNotes" value="${esc(x.Notes||'')}"></div></div><input type="hidden" id="inId" value="${esc(x['Internship ID']||'')}">`,'<button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveInternship()">Save Internship</button>');}
async function saveInternship(){try{await API.saveInternship(adminPin,{id:$('inId').value,academicYear:$('inYear').value,class:$('inClass').value,roll:$('inRoll').value,name:$('inName').value,trade:$('inTrade').value,organization:$('inOrg').value,role:$('inRole').value,mentor:$('inMentor').value,startDate:$('inStart').value,endDate:$('inEnd').value,duration:$('inDuration').value,status:$('inStatus').value,skillsLearned:$('inSkills').value,certificateId:$('inCert').value,evidenceUrl:$('inEvidence').value,verified:$('inVerified').checked,verifiedBy:'Admin / Vocational Teacher',notes:$('inNotes').value});closeModal();loadIndustryCenter();}catch(e){msg(e.message,'error');}} function editInternship(x){openInternshipForm(x)} async function deleteInternship(id){if(confirm('Delete internship?')){await API.deleteInternship(adminPin,id);loadIndustryCenter();}}
function openAttendance(activityId,type){modal('Attendance / Participation',`<p class="muted">Activity ID: <b>${esc(activityId)}</b></p><div class="grid"><div class="field"><label>Roll Number</label><input id="atRoll"></div><div class="field"><label>Student Name</label><input id="atName"></div><div class="field"><label>Academic Year</label><input id="atYear" value="2026-27"></div><div class="field"><label>Class</label><input id="atClass"></div><div class="field"><label>Attendance</label><select id="atPresent"><option>Present</option><option>Absent</option></select></div><div class="field"><label>Participation</label><input id="atParticipation" placeholder="Active / Good / Excellent"></div><div class="field"><label>Learning Outcome</label><input id="atOutcome"></div></div><button class="btn primary" onclick='saveAttendance("${esc(activityId)}","${esc(type)}")'>Save Student Attendance</button><div class="notice">Use this form repeatedly for each participating student. Records are centrally stored in Google Sheet.</div>`,'<button class="btn secondary" onclick="closeModal()">Close</button>');}
async function saveAttendance(activityId,type){try{const data={activityId,academicYear:$('atYear').value,class:$('atClass').value,roll:$('atRoll').value,name:$('atName').value,attendance:$('atPresent').value,participation:$('atParticipation').value,learningOutcome:$('atOutcome').value,verified:true,verifiedBy:'Admin / Vocational Teacher'};if(type==='Guest Lecture')await API.saveGuestAttendance(adminPin,data);else await API.saveVisitAttendance(adminPin,data);msg('Attendance saved.','success');$('atRoll').value='';$('atName').value='';}catch(e){msg(e.message,'error');}}

// ---------------- CENTRAL SKILL PASSPORT ----------------
async function loadSkillCenter(){
  const box=$('skillCenterRows'); if(!box)return;
  try{
    const rows=await API.getSkillRecords(adminPin, {search:$('skillCenterSearch')?.value.trim()||''});
    box.innerHTML=(rows||[]).map(x=>`<tr><td>${esc(x['Student Name'])}</td><td>${esc(x.Class)}</td><td>${esc(x['Roll Number'])}</td><td>${esc(x['Skill Name'])}</td><td>${esc(x.Level)}%</td><td>${String(x.Verified).toLowerCase()==='yes'?'✅ Verified':'⏳ Pending'}</td><td><button class="mini" onclick="editCentralSkill('${esc(x.ID)}')">Edit</button> <button class="mini danger" onclick="deleteCentralSkill('${esc(x.ID)}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="7">No central skill records yet.</td></tr>';
  }catch(e){box.innerHTML='<tr><td colspan="7">'+esc(e.message)+'</td></tr>';}
}
async function loadCertificatesCenter(){
  const box=$('certificateCenterRows'); if(!box)return;
  try{const rows=await API.getCertificates(adminPin,{search:$('certificateSearch')?.value.trim()||''});box.innerHTML=(rows||[]).map(x=>`<tr><td>${esc(x['Certificate ID'])}</td><td>${esc(x['Student Name'])}</td><td>${esc(x['Roll Number'])}</td><td>${esc(x['Certificate Title'])}</td><td>${esc(x['Issued By'])}</td><td>${esc(x['Verification Status'])}</td><td><button class="mini" onclick="printCentralCertificate(${JSON.stringify(x).replace(/</g,'\\u003c')})">Print</button> <button class="mini danger" onclick="deleteCentralCertificate('${esc(x['Certificate ID'])}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="7">No certificates issued yet.</td></tr>';}catch(e){box.innerHTML='<tr><td colspan="7">'+esc(e.message)+'</td></tr>';}
}
function openCentralSkillForm(){modal('Verify / Add Skill',`<div class="grid"><div class="field"><label>Academic Year</label><input id="csYear" value="2026-27"></div><div class="field"><label>Class</label><select id="csClass"><option>9th</option><option>10th</option><option>11th</option><option>12th</option></select></div><div class="field"><label>Roll Number</label><input id="csRoll"></div><div class="field"><label>Student Name</label><input id="csName"></div><div class="field"><label>Trade</label><input id="csTrade" value="IT-ITeS"></div><div class="field"><label>Skill</label><input id="csSkill" placeholder="e.g. Spreadsheet Skills"></div><div class="field"><label>Level (0-100)</label><input id="csLevel" type="number" min="0" max="100" value="70"></div><div class="field"><label>Evidence</label><input id="csEvidence" placeholder="Task / certificate / project reference"></div><div class="field"><label>Notes</label><input id="csNotes"></div></div><label><input id="csVerified" type="checkbox" checked> Verify this skill</label>`,'<button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveCentralSkill()">Save Skill</button>');}
async function saveCentralSkill(){try{await API.saveSkillRecord(adminPin,{academicYear:$('csYear').value,class:$('csClass').value,roll:$('csRoll').value.trim(),name:$('csName').value.trim(),trade:$('csTrade').value.trim(),skill:$('csSkill').value.trim(),level:Number($('csLevel').value),verified:$('csVerified').checked,verifiedBy:'Admin / Vocational Teacher',evidence:$('csEvidence').value.trim(),notes:$('csNotes').value.trim()});closeModal();msg('Skill saved centrally in Google Sheet.','success');loadSkillCenter();}catch(e){msg(e.message,'error');}}
async function deleteCentralSkill(id){if(!confirm('Delete this central skill record?'))return;try{await API.deleteSkillRecord(adminPin,id);msg('Skill record deleted.','success');loadSkillCenter();}catch(e){msg(e.message,'error');}}
function editCentralSkill(id){msg('To re-verify or change a skill, use + Verify / Add Skill and save the corrected record.','info');}
function openCertificateForm(){modal('Issue Skill Certificate',`<div class="grid"><div class="field"><label>Academic Year</label><input id="ccYear" value="2026-27"></div><div class="field"><label>Class</label><select id="ccClass"><option>9th</option><option>10th</option><option>11th</option><option>12th</option></select></div><div class="field"><label>Roll Number</label><input id="ccRoll"></div><div class="field"><label>Student Name</label><input id="ccName"></div><div class="field"><label>Trade</label><input id="ccTrade" value="IT-ITeS"></div><div class="field"><label>Certificate Title</label><input id="ccTitle" placeholder="Vocational Skill Achievement Certificate"></div><div class="field"><label>Skill / Competency</label><input id="ccSkill"></div><div class="field"><label>Level</label><input id="ccLevel" value="Verified"></div><div class="field"><label>Issued By</label><input id="ccIssuer" value="Vocational Teacher"></div><div class="field"><label>Valid Until</label><input id="ccValid"></div><div class="field"><label>Notes</label><input id="ccNotes"></div></div>`,'<button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="issueCentralCertificate()">Issue Certificate</button>');}
async function issueCentralCertificate(){try{const r=await API.issueCertificate(adminPin,{academicYear:$('ccYear').value,class:$('ccClass').value,roll:$('ccRoll').value.trim(),name:$('ccName').value.trim(),trade:$('ccTrade').value.trim(),title:$('ccTitle').value.trim(),skill:$('ccSkill').value.trim(),level:$('ccLevel').value.trim(),issuedBy:$('ccIssuer').value.trim(),validUntil:$('ccValid').value,notes:$('ccNotes').value.trim()});closeModal();msg('Certificate issued: '+r.id,'success');loadCertificatesCenter();}catch(e){msg(e.message,'error');}}
async function deleteCentralCertificate(id){if(!confirm('Delete this certificate?'))return;try{await API.deleteCertificate(adminPin,id);msg('Certificate deleted.','success');loadCertificatesCenter();}catch(e){msg(e.message,'error');}}
function printCentralCertificate(x){const w=window.open('','_blank');if(!w)return;w.document.write(`<!doctype html><html><head><title>${esc(x['Certificate ID'])}</title><style>body{font-family:Arial;padding:50px}.cert{border:8px double #1f3a5f;padding:55px;text-align:center;min-height:650px}.id{font-size:12px;color:#667085}.name{font-size:34px;font-weight:700;margin:24px}.title{font-size:26px;font-weight:700}.skill{font-size:20px;margin:25px}.row{display:flex;justify-content:space-between;margin-top:90px;font-size:14px}</style></head><body><div class="cert"><div class="id">CERTIFICATE ID: ${esc(x['Certificate ID'])}</div><h1>Govt. Sandipani HSS School Damoh</h1><div class="title">${esc(x['Certificate Title'])}</div><p>This certificate recognizes the vocational achievement of</p><div class="name">${esc(x['Student Name'])}</div><p>Class ${esc(x.Class)} • Roll No. ${esc(x['Roll Number'])} • ${esc(x.Trade)}</p><div class="skill"><b>Skill / Competency:</b><br>${esc(x['Skill/Competency']||'Vocational Skill')}</div><p>Level: ${esc(x.Level)} • Verification: ${esc(x['Verification Status'])}</p><div class="row"><span>Issued: ${esc(x['Issued At'])}</span><span>Issued By: ${esc(x['Issued By'])}</span></div></div><script>window.print()<\\/script></body></html>`);w.document.close();}


// ---------------- ADMISSION TEST & MERIT CENTER ----------------
let admissionTestsCache=[], admissionMeritCache=[], admissionSelectedTest='';
async function loadAdmissionCenter(){
  try{
    admissionTestsCache=await API.getAdmissionTests(adminPin)||[];
    const sel=$('admissionTestSelect');
    if(sel){const current=admissionSelectedTest||sel.value;sel.innerHTML='<option value="">Select Admission Test</option>'+admissionTestsCache.map(x=>`<option value="${esc(x['Test ID'])}">${esc(x['Academic Year'])} • ${esc(x.Class)} • ${esc(x.Trade)} • ${esc(x['Job Role'])} • ${esc(x['Test ID'])}</option>`).join('');if(current&&admissionTestsCache.some(x=>x['Test ID']===current))sel.value=current;}
    $('admissionTestRows').innerHTML=admissionTestsCache.map(x=>`<tr><td>${esc(x['Test ID'])}</td><td>${esc(x['Academic Year'])}</td><td>${esc(x.Class)}</td><td>${esc(x.Trade)}</td><td>${esc(x['Job Role'])}</td><td>${esc(x['Test Date'])}</td><td>${esc(x['Total Seats'])}</td><td>${esc(x['Max Marks'])}</td><td><span class="badge">${esc(x.Status)}</span></td><td><button class="mini" onclick='selectAdmissionTest("${esc(x['Test ID'])}")'>Open</button> <button class="mini" onclick='openAdmissionQuestions("${esc(x['Test ID'])}")'>Questions</button> <button class="mini" onclick='toggleAdmissionStatus("${esc(x['Test ID'])}")'>${String(x.Status).toLowerCase()==='open'?'Close':'Open'}</button> <button class="mini" onclick='editAdmissionTest(${JSON.stringify(x).replace(/</g,'\u003c')})'>Edit</button> <button class="mini danger" onclick='deleteAdmissionTest("${esc(x['Test ID'])}")'>Delete</button></td></tr>`).join('')||'<tr><td colspan="10">No admission tests created yet.</td></tr>';
    if(sel?.value) await loadAdmissionCandidates(); else clearAdmissionTables();
  }catch(e){msg(e.message,'error');}
}
function clearAdmissionTables(){if($('admissionCandidateRows'))$('admissionCandidateRows').innerHTML='<tr><td colspan="11">Select an admission test first.</td></tr>';if($('admissionMeritRows'))$('admissionMeritRows').innerHTML='<tr><td colspan="9">Select an admission test first.</td></tr>';['adTotal','adSeats','adSelected','adWaiting','adVacant'].forEach(id=>{if($(id))$(id).textContent='0';});}
function selectAdmissionTest(id){admissionSelectedTest=id;if($('admissionTestSelect'))$('admissionTestSelect').value=id;loadAdmissionCandidates();}

async function toggleAdmissionStatus(id){
  const x=admissionTestsCache.find(t=>t['Test ID']===id); if(!x)return;
  const next=String(x.Status).toLowerCase()==='open'?'Closed':'Open';
  if(!confirm((next==='Open'?'Open':'Close')+' this admission test for students?'))return;
  try{await API.saveAdmissionTest(adminPin,{id,academicYear:x['Academic Year'],class:x.Class,trade:x.Trade,jobRole:x['Job Role'],testDate:x['Test Date'],totalSeats:x['Total Seats'],maxMarks:x['Max Marks'],selectionRule:x['Selection Rule'],status:next,notes:x.Notes});msg('Admission test '+next.toLowerCase()+'.','success');await loadAdmissionCenter();}catch(e){msg(e.message,'error');}
}
async function openAdmissionQuestions(testId){
  const test=admissionTestsCache.find(t=>t['Test ID']===testId); if(!test)return;
  try{
    const qs=await API.getAdmissionQuestions(adminPin,testId)||[];
    const rows=qs.map(q=>`<tr><td>${esc(q['Question No'])}</td><td>${esc(q.Question)}</td><td>${esc(q['Option A'])} | ${esc(q['Option B'])} | ${esc(q['Option C'])} | ${esc(q['Option D'])}</td><td>${String.fromCharCode(65+Number(q.Correct||0))}</td><td>${esc(q.Marks)}</td><td><button class="mini" onclick='editAdmissionQuestion(${JSON.stringify(q).replace(/</g,'\\u003c')})'>Edit</button> <button class="mini danger" onclick='deleteAdmissionQuestion("${esc(q['Question ID'])}","${esc(testId)}")'>Delete</button></td></tr>`).join('')||'<tr><td colspan="6">No questions added yet.</td></tr>';
    const body=`<div class="notice"><b>${esc(test['Academic Year'])} • ${esc(test.Class)} • ${esc(test.Trade)}</b><br>Students see this test only while its status is <b>Open</b>. Add questions before opening it.</div><div class="table-wrap"><table class="admin-table"><thead><tr><th>#</th><th>Question</th><th>Options</th><th>Correct</th><th>Marks</th><th>Action</th></tr></thead><tbody>${rows}</tbody></table></div>`;
    modal('Admission Question Bank',body,`<button class="btn secondary" onclick="closeModal()">Close</button><button class="btn primary" onclick='addAdmissionQuestion(${JSON.stringify(testId)})'>+ Add Question</button>`);
  }catch(e){msg(e.message,'error');}
}
function admissionQuestionForm(q={},testId=''){
  return `<div class="grid"><div class="field"><label>Question No.</label><input id="aqNo" type="number" min="1" value="${esc(q['Question No']||1)}"></div><div class="field"><label>Marks</label><input id="aqMarks" type="number" min="1" value="${esc(q.Marks||1)}"></div><div class="field" style="grid-column:1/-1"><label>Question</label><textarea id="aqQuestion" rows="3">${esc(q.Question||'')}</textarea></div><div class="field"><label>Option A</label><input id="aqA" value="${esc(q['Option A']||'')}"></div><div class="field"><label>Option B</label><input id="aqB" value="${esc(q['Option B']||'')}"></div><div class="field"><label>Option C</label><input id="aqC" value="${esc(q['Option C']||'')}"></div><div class="field"><label>Option D</label><input id="aqD" value="${esc(q['Option D']||'')}"></div><div class="field"><label>Correct Answer</label><select id="aqCorrect">${['A','B','C','D'].map((v,i)=>`<option value="${i}" ${Number(q.Correct||0)===i?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Explanation (optional)</label><input id="aqExplanation" value="${esc(q.Explanation||'')}"></div></div><input type="hidden" id="aqId" value="${esc(q['Question ID']||'')}"><input type="hidden" id="aqTestId" value="${esc(testId||q['Test ID']||'')}">`;
}
function addAdmissionQuestion(testId){modal('Add Admission Question',admissionQuestionForm({},testId),`<button class="btn secondary" onclick='openAdmissionQuestions(${JSON.stringify(testId)})'>Back</button><button class="btn primary" onclick="saveAdmissionQuestion()">Save Question</button>`);}
function editAdmissionQuestion(q){modal('Edit Admission Question',admissionQuestionForm(q,q['Test ID']),`<button class="btn secondary" onclick='openAdmissionQuestions(${JSON.stringify(q['Test ID'])})'>Back</button><button class="btn primary" onclick="saveAdmissionQuestion()">Save Changes</button>`);}
async function saveAdmissionQuestion(){
  const testId=$('aqTestId').value;
  showAdminActionLoading($('aqId').value?'Saving question changes…':'Adding question…');
  try{await API.saveAdmissionQuestion(adminPin,{id:$('aqId').value,testId,questionNo:$('aqNo').value,question:$('aqQuestion').value,optionA:$('aqA').value,optionB:$('aqB').value,optionC:$('aqC').value,optionD:$('aqD').value,correct:$('aqCorrect').value,explanation:$('aqExplanation').value,marks:$('aqMarks').value});msg($('aqId').value?'Question updated successfully.':'Question added successfully.','success');await openAdmissionQuestions(testId);}catch(e){msg(e.message,'error');}finally{hideAdminActionLoading();}
}
async function deleteAdmissionQuestion(id,testId){if(!confirm('Delete this question?'))return;try{await API.deleteAdmissionQuestion(adminPin,id);await openAdmissionQuestions(testId);}catch(e){msg(e.message,'error');}}

function admissionTestForm(x={}){return `<div class="grid"><div class="field"><label>Academic Year</label><input id="adYear" value="${esc(x['Academic Year']||'2026-27')}"></div><div class="field"><label>Class</label><select id="adClass">${['9th','10th','11th','12th'].map(v=>`<option ${v===x.Class?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Trade</label><select id="adTrade"><option ${x.Trade==='IT-ITeS'?'selected':''}>IT-ITeS</option><option ${x.Trade==='Agriculture'?'selected':''}>Agriculture</option></select></div><div class="field"><label>Job Role</label><input id="adJob" value="${esc(x['Job Role']||'')}" placeholder="Enter/select job role"></div><div class="field"><label>Test Date</label><input id="adDate" type="date" value="${esc(x['Test Date']||'')}"></div><div class="field"><label>Total Seats</label><input id="adSeatsInput" type="number" min="1" value="${esc(x['Total Seats']||30)}"></div><div class="field"><label>Maximum Marks</label><input id="adMax" type="number" min="1" value="${esc(x['Max Marks']||100)}"></div><div class="field"><label>Selection Rule</label><input id="adRule" value="${esc(x['Selection Rule']||'Highest marks / merit rank')}"></div><div class="field"><label>Status</label><select id="adStatus"><option>Open</option><option ${x.Status==='Closed'?'selected':''}>Closed</option><option ${x.Status==='Draft'?'selected':''}>Draft</option></select></div><div class="field"><label>Notes</label><input id="adNotes" value="${esc(x.Notes||'')}"></div></div><input type="hidden" id="adId" value="${esc(x['Test ID']||'')}"><div class="notice">Seat count is used automatically for Selected/Waiting. The merit calculation itself is based on marks/percentage; equal percentages receive the same rank.</div>`;}
function openAdmissionTestForm(x={}){modal(x['Test ID']?'Edit Admission Test':'Create Admission Test',admissionTestForm(x),'<button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveAdmissionTest()">Save Test</button>');}
function editAdmissionTest(x){openAdmissionTestForm(x)}
async function saveAdmissionTest(){
  const isEdit=!!$('adId').value;showAdminActionLoading(isEdit?'Updating admission test…':'Creating admission test…');
  try{const r=await API.saveAdmissionTest(adminPin,{id:$('adId').value,academicYear:$('adYear').value,class:$('adClass').value,trade:$('adTrade').value,jobRole:$('adJob').value,testDate:$('adDate').value,totalSeats:$('adSeatsInput').value,maxMarks:$('adMax').value,selectionRule:$('adRule').value,status:$('adStatus').value,notes:$('adNotes').value});admissionSelectedTest=r.id;closeModal();msg(isEdit?'Admission test updated successfully.':'Admission test created successfully.','success');await loadAdmissionCenter();selectAdmissionTest(r.id);}catch(e){msg(e.message,'error');}finally{hideAdminActionLoading();}
}
async function deleteAdmissionTest(id){if(!confirm('Delete this admission test and all its candidate/merit records? This action cannot be undone.'))return;try{await API.deleteAdmissionTest(adminPin,id);if(admissionSelectedTest===id)admissionSelectedTest='';msg('Admission test and linked records deleted.','success');loadAdmissionCenter();}catch(e){msg(e.message,'error');}}
function admissionCandidateForm(x={}){const t=admissionTestsCache.find(a=>a['Test ID']===admissionSelectedTest)||{};return `<div class="grid"><div class="field"><label>Admission Test</label><select id="acTest">${admissionTestsCache.map(a=>`<option value="${esc(a['Test ID'])}" ${a['Test ID']===(x['Test ID']||admissionSelectedTest)?'selected':''}>${esc(a['Academic Year'])} • ${esc(a.Class)} • ${esc(a.Trade)} • ${esc(a['Job Role'])}</option>`).join('')}</select></div><div class="field"><label>Application No.</label><input id="acApp" value="${esc(x['Application No']||'')}"></div><div class="field"><label>Roll Number</label><input id="acRoll" value="${esc(x['Roll Number']||'')}"></div><div class="field"><label>Student Name</label><input id="acName" value="${esc(x['Student Name']||'')}"></div><div class="field"><label>Father's Name</label><input id="acFather" value="${esc(x["Father's Name"]||'')}"></div><div class="field"><label>Mobile</label><input id="acMobile" inputmode="numeric" value="${esc(x.Mobile||'')}"></div><div class="field"><label>Test Marks</label><input id="acMarks" type="number" min="0" value="${esc(x.Marks??'')}"></div><div class="field"><label>Tie Breaker (optional)</label><input id="acTie" type="number" value="${esc(x['Tie Breaker']||0)}"></div><div class="field"><label>Notes</label><input id="acNotes" value="${esc(x.Notes||'')}"></div></div><input type="hidden" id="acId" value="${esc(x['Candidate ID']||'')}"><div class="notice">The maximum marks are taken from the selected test. Rank and Selected/Waiting status are recalculated automatically after every save/delete.</div>`;}
function openAdmissionCandidateForm(x={}){if(!admissionTestsCache.length)return msg('Create an admission test first.','error');modal(x['Candidate ID']?'Edit Candidate':'Add Admission Candidate',admissionCandidateForm(x),'<button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveAdmissionCandidate()">Save Candidate</button>');}
async function saveAdmissionCandidate(){try{const r=await API.saveAdmissionCandidate(adminPin,{id:$('acId').value,testId:$('acTest').value,applicationNo:$('acApp').value,rollNumber:$('acRoll').value,studentName:$('acName').value,fatherName:$('acFather').value,mobile:$('acMobile').value,marks:$('acMarks').value,tieBreaker:$('acTie').value,notes:$('acNotes').value});admissionSelectedTest=$('acTest').value;closeModal();msg('Candidate saved and merit recalculated.','success');await loadAdmissionCandidates();}catch(e){msg(e.message,'error');}}
async function loadAdmissionCandidates(){const tid=$('admissionTestSelect')?.value||admissionSelectedTest;if(!tid)return clearAdmissionTables();admissionSelectedTest=tid;const q=($('admissionSearch')?.value||'').trim().toLowerCase();try{const rows=await API.getAdmissionCandidates(adminPin,tid);const filtered=(rows||[]).filter(x=>!q||[x['Application No'],x['Roll Number'],x['Student Name'],x["Father's Name"]].some(v=>String(v||'').toLowerCase().includes(q)));$('admissionCandidateRows').innerHTML=filtered.map(x=>`<tr><td>${esc(x.Rank||'—')}</td><td>${esc(x['Application No'])}</td><td>${esc(x['Roll Number']||'—')}</td><td>${esc(x['Student Name'])}</td><td>${esc(x["Father's Name"])}</td><td>${esc(x.Trade)}</td><td>${esc(x['Job Role'])}</td><td>${esc(x.Marks)} / ${esc(x['Max Marks'])}</td><td>${esc(x.Percentage)}%</td><td><span class="badge">${esc(x.Status)}</span></td><td><button class="mini" onclick='openAdmissionCandidateForm(${JSON.stringify(x).replace(/</g,'\\u003c')})'>Edit</button> <button class="mini danger" onclick='deleteAdmissionCandidate("${esc(x['Candidate ID'])}")'>Delete</button></td></tr>`).join('')||'<tr><td colspan="11">No candidates found for this test.</td></tr>';await refreshAdmissionMerit();}catch(e){msg(e.message,'error');}}
async function refreshAdmissionMerit(){if(!admissionSelectedTest)return clearAdmissionTables();try{const r=await API.getAdmissionMerit(adminPin,admissionSelectedTest);admissionMeritCache=r.merit||[];$('adTotal').textContent=admissionMeritCache.length;$('adSeats').textContent=r.seats||0;$('adSelected').textContent=r.seatsFilled||0;$('adWaiting').textContent=Math.max(0,admissionMeritCache.length-(r.seatsFilled||0));$('adVacant').textContent=r.vacant||0;$('admissionMeritRows').innerHTML=admissionMeritCache.map(x=>`<tr><td>${esc(x.rank)}</td><td>${esc(x.applicationNo)}</td><td>${esc(x.rollNumber||'—')}</td><td>${esc(x.studentName)}</td><td>${esc(x.fatherName)}</td><td>${esc(x.marks)}</td><td>${esc(x.maxMarks)}</td><td>${esc(x.percentage)}%</td><td><span class="badge">${esc(x.status)}</span></td></tr>`).join('')||'<tr><td colspan="9">No merit records yet.</td></tr>';}catch(e){msg(e.message,'error');}}
async function deleteAdmissionCandidate(id){if(!confirm('Delete this candidate? Merit will be recalculated automatically.'))return;try{await API.deleteAdmissionCandidate(adminPin,id);msg('Candidate deleted and merit recalculated.','success');loadAdmissionCandidates();}catch(e){msg(e.message,'error');}}
function downloadAdmissionCSV(){if(!admissionMeritCache.length)return msg('No merit records to download.','error');const cols=['Rank','Application No.','Roll Number','Student Name',"Father's Name",'Marks','Max Marks','Percentage','Status','Trade','Job Role'];const rows=admissionMeritCache.map(x=>[x.rank,x.applicationNo,x.rollNumber,x.studentName,x.fatherName,x.marks,x.maxMarks,x.percentage,x.status,x.trade,x.jobRole]);const csv=[cols, ...rows].map(r=>r.map(csvEscape).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='Sandipani_Admission_Merit_List.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);msg('Merit CSV downloaded.','success');}
function printAdmissionMerit(){if(!admissionMeritCache.length)return msg('No merit records to print.','error');const t=admissionTestsCache.find(x=>x['Test ID']===admissionSelectedTest)||{};const w=window.open('','_blank');if(!w)return;const rows=admissionMeritCache.map(x=>`<tr><td>${esc(x.rank)}</td><td>${esc(x.applicationNo)}</td><td>${esc(x.rollNumber||'')}</td><td>${esc(x.studentName)}</td><td>${esc(x.fatherName)}</td><td>${esc(x.marks)}</td><td>${esc(x.maxMarks)}</td><td>${esc(x.percentage)}%</td><td>${esc(x.status)}</td></tr>`).join('');w.document.write(`<!doctype html><html><head><title>Admission Merit List</title><style>body{font-family:Arial;margin:30px;color:#111}h1,h2{text-align:center;margin:4px}.meta{text-align:center;margin:10px 0 20px;color:#444}table{width:100%;border-collapse:collapse;font-size:12px}th,td{border:1px solid #222;padding:7px;text-align:left}th{background:#eee}.sign{display:flex;justify-content:space-between;margin-top:80px}.sign div{width:35%;text-align:center}.sign small{display:block;margin-top:8px}</style></head><body><h1>Govt. Sandipani HSS School Damoh</h1><h2>Admission Test Merit List</h2><div class="meta">Academic Year: ${esc(t['Academic Year'])} • Class: ${esc(t.Class)} • Trade: ${esc(t.Trade)} • Job Role: ${esc(t['Job Role'])}<br>Test Date: ${esc(t['Test Date'])} • Total Seats: ${esc(t['Total Seats'])} • Maximum Marks: ${esc(t['Max Marks'])}</div><table><thead><tr><th>Rank</th><th>Application</th><th>Roll</th><th>Student</th><th>Father</th><th>Marks</th><th>Max</th><th>%</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table><div class="sign"><div><b>Signature of Teacher</b><small>________________________</small></div><div><b>Principal Seal & Signature</b><small>________________________</small></div></div><script>window.print()<\/script></body></html>`);w.document.close();}
