(function(){
'use strict';
const COURSES=[
 {id:'it9-digital',trade:'IT-ITeS',class:'9th',medium:['Hindi','English'],icon:'💻',level:'Foundation',title:'Digital Foundations',desc:'Computer basics, digital devices, safe internet use and productive digital habits.',lessons:[['01','Computer & Digital Devices','Understand the role of computers, common devices and basic terminology.'],['02','Files & Folders','Create, rename, organise and manage files and folders.'],['03','Internet Basics','Learn browsers, search, URLs and responsible internet use.'],['04','Digital Safety','Passwords, privacy, phishing awareness and safe online behaviour.'],['05','Everyday Digital Tasks','Email, downloads, uploads and basic document handling.']]},
 {id:'it9-office',trade:'IT-ITeS',class:'9th',medium:['Hindi','English'],icon:'🖥️',level:'Foundation',title:'Office Productivity Basics',desc:'Build a practical base in documents, spreadsheets, presentations and data handling.',lessons:[['01','Documents','Create and format a clean school document.'],['02','Spreadsheets','Enter data, format cells and understand rows and columns.'],['03','Presentation Basics','Build a simple presentation with readable slides.'],['04','Data Organisation','Sort, filter and maintain clean tabular data.'],['05','Practical Project','Create a small school information worksheet.']]},
 {id:'it10-ddeo',trade:'IT-ITeS',class:'10th',medium:['Hindi','English'],icon:'⌨️',level:'Skill',title:'Domestic Data Entry Operator',desc:'Practice the core workflow of accurate data entry, documents and office communication.',lessons:[['01','Data Entry Fundamentals','Accuracy, speed, keyboard discipline and structured data entry.'],['02','Typing Practice','Improve touch-typing habits, accuracy and timed practice.'],['03','Word Processing','Formatting, tables, page setup and professional documents.'],['04','Spreadsheet Data Entry','Clean tables, basic formulas and data formatting.'],['05','Email & Digital Communication','Compose clear professional messages and manage attachments.'],['06','Mini Office Project','Complete a realistic school-office data entry task.']]},
 {id:'it10-internet',trade:'IT-ITeS',class:'10th',medium:['Hindi','English'],icon:'🌐',level:'Skill',title:'Internet & Digital Services',desc:'Use online services confidently while protecting personal information and accounts.',lessons:[['01','Search Skills','Use effective keywords and evaluate search results.'],['02','Online Forms','Enter, verify and submit digital forms accurately.'],['03','Cloud & Sharing','Understand online storage, sharing permissions and links.'],['04','Cyber Awareness','Recognise common scams and suspicious messages.'],['05','Digital Etiquette','Professional communication and responsible digital behaviour.']]},
 {id:'it11-web',trade:'IT-ITeS',class:'11th',medium:['Hindi','English'],icon:'🌐',level:'Advanced',title:'Web & Digital Creation',desc:'Move from using digital tools to creating useful digital content and simple web pages.',lessons:[['01','Web Concepts','Understand websites, browsers, domains and hosting at a basic level.'],['02','HTML Structure','Create a simple semantic web page.'],['03','CSS Styling','Style text, cards, layouts and responsive sections.'],['04','Digital Content','Plan accessible, useful and organised digital content.'],['05','Project','Create a small school or vocational information page.']]},
 {id:'it11-data',trade:'IT-ITeS',class:'11th',medium:['Hindi','English'],icon:'📊',level:'Advanced',title:'Data & Spreadsheet Skills',desc:'Build stronger spreadsheet and data-handling skills for real workplace tasks.',lessons:[['01','Data Types','Text, numbers, dates and structured records.'],['02','Formulas','Use basic formulas and references correctly.'],['03','Sorting & Filtering','Find, clean and analyse structured data.'],['04','Charts','Turn simple data into readable charts.'],['05','Mini Dashboard','Create a compact class-data dashboard.']]},
 {id:'it12-career',trade:'IT-ITeS',class:'12th',medium:['Hindi','English'],icon:'🚀',level:'Career',title:'Workplace Digital Skills',desc:'Prepare for office, data and digital roles through practical workplace scenarios.',lessons:[['01','Professional Documents','Create polished resumes, letters and reports.'],['02','Advanced Spreadsheet Workflow','Use formulas, validation and structured data practices.'],['03','Data Quality','Check accuracy, duplicates, missing values and consistency.'],['04','Workplace Communication','Professional email, meetings and digital collaboration.'],['05','Portfolio Project','Create a small evidence-based digital work portfolio.'],['06','Job Readiness','Map skills to entry-level digital roles and next steps.']]},
 {id:'ag9-foundation',trade:'Agriculture',class:'9th',medium:['Hindi','English'],icon:'🌱',level:'Foundation',title:'Agriculture Foundations',desc:'Understand soil, crops, farm tools and basic agricultural practices.',lessons:[['01','Introduction to Agriculture','Agriculture, its importance and major activities.'],['02','Soil Basics','Soil properties, organic matter and simple observation.'],['03','Seeds & Sowing','Seed quality, sowing methods and care.'],['04','Farm Tools','Identify common tools and safe handling practices.'],['05','Practical Observation','Record a simple field or garden observation.']]},
 {id:'ag10-crops',trade:'Agriculture',class:'10th',medium:['Hindi','English'],icon:'🌾',level:'Skill',title:'Crop Production',desc:'Learn crop planning, nursery work, cultivation and basic crop care.',lessons:[['01','Crop Planning','Season, crop selection and basic planning.'],['02','Nursery Management','Seedlings, beds, watering and care.'],['03','Plant Nutrition','Basic nutrient needs and responsible management.'],['04','Irrigation','Water requirements and efficient irrigation practices.'],['05','Crop Protection','Observation-based identification and safe practices.']]},
 {id:'ag11-floriculture',trade:'Agriculture',class:'11th',medium:['Hindi','English'],icon:'🌸',level:'Advanced',title:'Floriculture & Nursery',desc:'Develop practical understanding of flowers, nursery management and plant care.',lessons:[['01','Floriculture Basics','Scope, importance and types of ornamental crops.'],['02','Propagation','Basic propagation methods and nursery handling.'],['03','Plant Care','Watering, nutrition, training and sanitation.'],['04','Flower Harvest','Timing, handling and quality considerations.'],['05','Nursery Project','Plan and document a small nursery activity.']]},
 {id:'ag12-agrient',trade:'Agriculture',class:'12th',medium:['Hindi','English'],icon:'🚜',level:'Career',title:'Applied Agriculture & Enterprise',desc:'Connect practical agriculture skills with record keeping, planning and enterprise thinking.',lessons:[['01','Farm Records','Maintain basic input, activity and output records.'],['02','Cost & Planning','Understand simple cost and activity planning.'],['03','Post-Harvest Handling','Basic quality, storage and handling concepts.'],['04','Enterprise Basics','Explore small-scale agriculture enterprise ideas.'],['05','Project & Presentation','Prepare and present a practical agriculture project.']]}
];
const state={q:'',cls:'all',trade:'all',medium:'all'};
const key='sandipani_learning_progress_v1'; const savedKey='sandipani_learning_saved_v1';
let progress=JSON.parse(localStorage.getItem(key)||'{}'); let saved=JSON.parse(localStorage.getItem(savedKey)||'[]');
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function save(){localStorage.setItem(key,JSON.stringify(progress));localStorage.setItem(savedKey,JSON.stringify(saved));renderStats();renderProgress();}
function coursePct(c){return Math.round(((c.lessons||[]).filter(x=>progress[c.id+'::'+x[0]]).length/(c.lessons.length||1))*100)}
function filtered(){return COURSES.filter(c=>(state.cls==='all'||c.class===state.cls)&&(state.trade==='all'||c.trade===state.trade)&&(state.medium==='all'||c.medium.includes(state.medium))&&(!state.q||[c.title,c.desc,c.trade,c.class,...c.lessons.map(x=>x[1])].join(' ').toLowerCase().includes(state.q.toLowerCase())))}
function renderCourses(){const list=filtered(); $('courseGrid').innerHTML=list.map(c=>{const pct=coursePct(c);return `<article class="course-card"><div class="course-top"><span class="course-icon">${c.icon}</span><span class="course-level">${esc(c.level)}</span></div><div class="course-meta"><span>${esc(c.class)}</span><span>${esc(c.trade)}</span><span>${c.lessons.length} lessons</span></div><h3>${esc(c.title)}</h3><p>${esc(c.desc)}</p><div class="course-progress"><div><span>${pct}% complete</span><span>${c.lessons.filter(x=>progress[c.id+'::'+x[0]]).length}/${c.lessons.length}</span></div><div class="progress-track"><i style="width:${pct}%"></i></div></div><div class="course-actions"><button class="learn-btn small" data-open="${c.id}">${pct?'Continue':'Start Learning'} →</button><button class="save-course ${saved.includes(c.id)?'saved':''}" data-save="${c.id}" title="Save course">${saved.includes(c.id)?'★':'☆'}</button></div></article>`}).join(''); $('emptyState').classList.toggle('hidden',!!list.length); bindCourseButtons();}
function bindCourseButtons(){document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openCourse(b.dataset.open));document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{const id=b.dataset.save;saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];save();renderCourses();});}
function openCourse(id,startIndex=0){const c=COURSES.find(x=>x.id===id);if(!c)return;let i=Math.max(0,Math.min(startIndex,c.lessons.length-1));const render=()=>{const l=c.lessons[i],done=!!progress[c.id+'::'+l[0]]; $('lessonBody').innerHTML=`<div class="lesson-head"><span class="course-icon">${c.icon}</span><div><span>${esc(c.class)} • ${esc(c.trade)} • ${esc(c.level)}</span><h2>${esc(c.title)}</h2></div></div><div class="lesson-count">Lesson ${i+1} of ${c.lessons.length}<span>${done?'✓ Completed':''}</span></div><div class="lesson-content"><span class="lesson-number">${esc(l[0])}</span><h3>${esc(l[1])}</h3><p>${esc(l[2])}</p><div class="lesson-box"><b>Learning action</b><p>Read the topic, discuss an example with your teacher, then complete a related practical activity from your class workbook.</p></div><div class="lesson-box"><b>Quick check</b><p>Can you explain the main idea in your own words and give one real-life example?</p></div></div><div class="lesson-footer"><button class="learn-btn small secondary" id="markDone">${done?'✓ Completed':'Mark as complete'}</button><div class="lesson-nav"><button class="lesson-arrow" id="prev" ${i===0?'disabled':''}>←</button><button class="lesson-arrow" id="next">${i===c.lessons.length-1?'Finish':'Next →'}</button></div></div>`;$('lessonModal').classList.remove('hidden');$('markDone').onclick=()=>{progress[c.id+'::'+l[0]]=true;save();render();renderCourses();};$('prev').onclick=()=>{if(i>0){i--;render();}};$('next').onclick=()=>{if(i<c.lessons.length-1){i++;render();}else{$('lessonModal').classList.add('hidden');}};};render();}
function renderStats(){const total=COURSES.reduce((n,c)=>n+c.lessons.length,0),done=Object.values(progress).filter(Boolean).length,pct=total?Math.round(done/total*100):0;$('overallPct').textContent=pct+'%';$('overallBar').style.width=pct+'%';$('completedCount').textContent=done;$('savedCount').textContent=saved.length;$('courseCount').textContent=COURSES.length;}
function renderProgress(){const list=COURSES.filter(c=>saved.includes(c.id)||coursePct(c)>0).sort((a,b)=>coursePct(b)-coursePct(a)).slice(0,6);$('progressGrid').innerHTML=list.length?list.map(c=>{const pct=coursePct(c);return `<div class="progress-card"><div class="pc-icon">${c.icon}</div><div><b>${esc(c.title)}</b><small>${esc(c.class)} • ${esc(c.trade)}</small><div class="progress-track"><i style="width:${pct}%"></i></div></div><button class="learn-btn tiny" data-progress="${c.id}">${pct?'Continue':'Start'}</button></div>`}).join(''):`<div class="no-progress"><div>📚</div><b>No course started yet</b><span>Choose a course above and your learning journey will appear here.</span></div>`;document.querySelectorAll('[data-progress]').forEach(b=>b.onclick=()=>openCourse(b.dataset.progress));}
function filters(){state.q=$('searchInput').value.trim();state.cls=$('classFilter').value;state.trade=$('tradeFilter').value;state.medium=$('mediumFilter').value;document.querySelectorAll('.trade-tab').forEach(x=>x.classList.toggle('active',x.dataset.trade===state.trade));renderCourses();}
$('searchInput').oninput=filters;$('classFilter').onchange=filters;$('tradeFilter').onchange=filters;$('mediumFilter').onchange=filters;$('resetFilters').onclick=()=>{$('searchInput').value='';$('classFilter').value='all';$('tradeFilter').value='all';$('mediumFilter').value='all';filters();};document.querySelectorAll('.trade-tab').forEach(b=>b.onclick=()=>{$('tradeFilter').value=b.dataset.trade;filters();});$('lessonClose').onclick=()=>$('lessonModal').classList.add('hidden');document.querySelector('[data-close]').onclick=()=>$('lessonModal').classList.add('hidden');$('continueBtn').onclick=()=>{const c=COURSES.find(x=>coursePct(x)>0)||COURSES.find(x=>saved.includes(x.id));if(c){document.getElementById('catalog').scrollIntoView({behavior:'smooth'});setTimeout(()=>openCourse(c.id),350);}else document.getElementById('catalog').scrollIntoView({behavior:'smooth'});};$('learnMenu').onclick=()=>document.querySelector('.learning-nav nav').classList.toggle('open');
renderCourses();renderStats();renderProgress();
})();
