(function(){
'use strict';
const KEY='sandipani_practical_lab_v1';
const passages=[
'The computer is a useful tool for creating documents, managing data and communicating information. Accurate typing and careful checking are important workplace skills.',
'Digital data entry requires attention to detail. A good operator checks names, numbers, dates and contact information before submitting a record.',
'Office productivity improves when files are organised, information is entered accurately and simple spreadsheet calculations are used correctly.'
];
const state={active:null,timer:null,seconds:0,start:0,typed:0};
function get(){try{return JSON.parse(localStorage.getItem(KEY))||{history:[]}}catch(e){return{history:[]}}}
function save(d){localStorage.setItem(KEY,JSON.stringify(d));renderStats();renderHistory()}
function addAttempt(type,score,detail){const d=get();d.history.unshift({type,score,detail:detail||'',date:new Date().toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})});d.history=d.history.slice(0,30);save(d)}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderStats(){const h=get().history;const scores=h.map(x=>Number(x.score)||0);const best=scores.length?Math.max(...scores):0;const avg=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0;document.getElementById('attempts').textContent=h.length;document.getElementById('bestScore').textContent=best;document.getElementById('mastery').textContent=avg+'%';document.getElementById('minutes').textContent=Math.max(0,Math.round(h.reduce((a,x)=>a+(Number(x.detailMinutes)||0),0)))}
function renderHistory(){const el=document.getElementById('history'),h=get().history;if(!h.length){el.innerHTML='<div class="history-empty">🧪<b>No practical attempts yet</b><span>Complete a module above and your result will appear here.</span></div>';return}el.innerHTML=h.map(x=>`<div class="history-row"><div class="history-icon">${x.type==='Typing'?'⌨️':x.type==='Data Entry'?'🧾':'📊'}</div><div><b>${esc(x.type)}</b><small>${esc(x.date)} • ${esc(x.detail||'Practice completed')}</small></div><strong>${x.score}/100</strong></div>`).join('')}
function open(type){state.active=type;const body=document.getElementById('labBody');document.getElementById('labModal').classList.remove('hidden');if(type==='typing')typing(body);if(type==='data')dataEntry(body);if(type==='office')office(body)}
function close(){stopTimer();document.getElementById('labModal').classList.add('hidden')}
function stopTimer(){if(state.timer){clearInterval(state.timer);state.timer=null}}
function typing(el){const passage=passages[Math.floor(Math.random()*passages.length)];el.innerHTML=`<div class="modal-kicker">TYPING ACCURACY TEST</div><h2>Type the passage exactly</h2><p class="task-note">You have <b>60 seconds</b>. Accuracy matters more than speed.</p><div class="typing-passage" id="typingPassage">${esc(passage)}</div><textarea id="typingInput" class="typing-input" placeholder="Start typing here..." spellcheck="false"></textarea><div class="timer-line"><b id="typingTimer">60</b><span>seconds left</span><button class="lab-btn primary" id="typingStart">Start timer</button></div><div id="typingResult"></div>`;document.getElementById('typingStart').onclick=()=>startTyping(passage)}
function startTyping(passage){const input=document.getElementById('typingInput'),btn=document.getElementById('typingStart');if(state.timer)return;state.seconds=60;state.start=Date.now();input.disabled=false;input.focus();btn.disabled=true;state.timer=setInterval(()=>{state.seconds--;document.getElementById('typingTimer').textContent=state.seconds;if(state.seconds<=0)finishTyping(passage)},1000);input.oninput=()=>{if(input.value.length>=passage.length)finishTyping(passage)}}
function finishTyping(passage){stopTimer();const input=document.getElementById('typingInput');if(!input)return;input.disabled=true;const val=input.value;let correct=0;for(let i=0;i<Math.min(val.length,passage.length);i++)if(val[i]===passage[i])correct++;const accuracy=val.length?Math.round(correct/Math.max(val.length,passage.length)*100):0;const elapsed=Math.max(1,(Date.now()-state.start)/1000);const words=val.trim()?val.trim().split(/\s+/).length:0;const wpm=Math.round(words/(elapsed/60));const score=Math.max(0,Math.min(100,Math.round(accuracy*.7+Math.min(wpm,60)/60*30)));document.getElementById('typingResult').innerHTML=resultBox(score,`Accuracy ${accuracy}% • ${wpm} WPM • ${Math.abs(passage.length-val.length)} character difference`);addAttempt('Typing',score,`Accuracy ${accuracy}% • ${wpm} WPM`)}
function dataEntry(el){const record={name:'Aarav Sharma',father:'Rakesh Sharma',mobile:'9876543210',className:'10th',roll:'1024',trade:'IT-ITeS'};el.innerHTML=`<div class="modal-kicker">DATA ENTRY CHALLENGE</div><h2>Enter the source record</h2><p class="task-note">Enter every field exactly as shown. Your score rewards accuracy and completeness.</p><div class="source-record">${Object.entries(record).map(([k,v])=>`<div><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join('')}</div><div class="entry-grid">${Object.keys(record).map(k=>`<label>${esc(k)}<input data-key="${k}" autocomplete="off"></label>`).join('')}</div><button class="lab-btn primary" id="checkData">Check & Submit</button><div id="dataResult"></div>`;document.getElementById('checkData').onclick=()=>{let correct=0,total=Object.keys(record).length;document.querySelectorAll('[data-key]').forEach(i=>{const ok=i.value.trim().toLowerCase()===record[i.dataset.key].toLowerCase();if(ok)correct++;i.classList.toggle('ok',ok);i.classList.toggle('bad',!ok)});const score=Math.round(correct/total*100);document.getElementById('dataResult').innerHTML=resultBox(score,`${correct}/${total} fields correct`);addAttempt('Data Entry',score,`${correct}/${total} fields correct`)}}
function office(el){el.innerHTML=`<div class="modal-kicker">SPREADSHEET PRACTICE</div><h2>Complete the mini worksheet</h2><p class="task-note">Enter the four quantities and prices. Then calculate each total, Grand Total and Average.</p><div class="sheet-wrap"><table class="practice-sheet"><thead><tr><th>Item</th><th>Qty</th><th>Price</th><th>Total</th></tr></thead><tbody id="sheetRows">${[['Notebook',4,55],['Pen Set',3,40],['Folder',5,30],['USB Drive',2,450]].map((r,i)=>`<tr><td>${r[0]}</td><td><input class="qty" value="${r[1]}" data-i="${i}"></td><td><input class="price" value="${r[2]}" data-i="${i}"></td><td><input class="total" data-i="${i}" placeholder="calculate"></td></tr>`).join('')}</tbody></table></div><div class="formula-task"><label>Grand Total <input id="grand" placeholder="enter total"></label><label>Average <input id="avg" placeholder="enter average"></label></div><button class="lab-btn primary" id="checkSheet">Check Worksheet</button><div id="sheetResult"></div>`;document.getElementById('checkSheet').onclick=checkSheet}
function checkSheet(){let rows=[...document.querySelectorAll('#sheetRows tr')],score=0;rows.forEach(tr=>{const q=Number(tr.querySelector('.qty').value),p=Number(tr.querySelector('.price').value),expected=q*p,val=Number(tr.querySelector('.total').value);if(val===expected)score+=15});const expectedGrand=rows.reduce((s,tr)=>s+Number(tr.querySelector('.qty').value)*Number(tr.querySelector('.price').value),0),expectedAvg=expectedGrand/rows.length;const g=Number(document.getElementById('grand').value),a=Number(document.getElementById('avg').value);if(g===expectedGrand)score+=20;if(Math.abs(a-expectedAvg)<0.01)score+=20;score=Math.min(100,score);document.getElementById('sheetResult').innerHTML=resultBox(score,`Grand Total should be ${expectedGrand}; Average ${expectedAvg.toFixed(2)}`);addAttempt('Office Productivity',score,`Worksheet ${score}%`)}
function resultBox(score,text){return `<div class="result-box"><div><b>${score}/100</b><span>${score>=90?'Excellent':score>=75?'Strong':score>=60?'Developing':'Practice again'}</span></div><p>${esc(text)}</p></div>`}
document.addEventListener('click',e=>{const openBtn=e.target.closest('[data-open]');if(openBtn)open(openBtn.dataset.open);if(e.target.closest('[data-close]'))close();});
document.getElementById('moduleFilter').onchange=e=>{document.querySelectorAll('.lab-card').forEach(c=>c.style.display=e.target.value==='all'||c.dataset.module===e.target.value?'':'none')};
document.getElementById('clearRecord').onclick=()=>{if(confirm('Clear all local practical records?')){localStorage.removeItem(KEY);renderStats();renderHistory()}};
document.getElementById('labMenu').onclick=()=>document.querySelector('.lab-nav nav').classList.toggle('open');
(async function loadCentralPractical(){try{if(typeof API!=='undefined'){const r=await API.getPracticalPublic();const mods=(r&&r.modules)||[];mods.forEach(m=>{const card=[...document.querySelectorAll('.lab-card')].find(c=>c.dataset.module===String(m.Module));if(card){const h=card.querySelector('h3'),p=card.querySelector('p'),tag=card.querySelector('.lab-tag');if(h&&m.Title)h.textContent=m.Title;if(p&&m.Description)p.textContent=m.Description;if(tag&&m.Module)tag.textContent=String(m.Module).toUpperCase()+' • CENTRAL';}});}}catch(e){console.warn('Central Practical metadata unavailable; using built-in lab.',e)}renderStats();renderHistory();})();
})();
