(function(){'use strict';
let BUILTIN=[
{id:'it9-digital-q1',class:'9th',trade:'IT-ITeS',unit:'Digital Foundations',mode:'practice',time:0,questions:[
['Which device is mainly used to enter text into a computer?',['Monitor','Keyboard','Speaker','Projector'],1,'A keyboard is an input device used to enter text and commands.'],
['Which is a strong password practice?',['Use your name','Use 123456','Use a long unique password','Share it with friends'],2,'A long, unique password is safer than common or reused passwords.'],
['What does a web browser help you do?',['Browse websites','Print electricity','Repair hardware','Create a cable'],0,'A browser is software used to access and view websites.'],
['Which action helps protect privacy online?',['Share OTP','Use privacy controls','Post passwords','Open every link'],1,'Privacy controls help limit unnecessary exposure of personal information.'],
['A folder is mainly used to…',['Organise files','Increase screen size','Charge a laptop','Connect speakers'],0,'Folders organise files into a manageable structure.']]},
{id:'it10-ddeo-q1',class:'10th',trade:'IT-ITeS',unit:'Domestic Data Entry Operator',mode:'timed',time:120,questions:[
['What is the most important quality in data entry?',['Guessing','Accuracy','Decoration','Speed only'],1,'Accurate data is essential; speed should not reduce correctness.'],
['Which key moves the cursor to the next field in many forms?',['Tab','Esc','Caps Lock','Print Screen'],0,'Tab commonly moves focus to the next form field.'],
['What should you do with a duplicate record?',['Ignore it','Check and resolve it','Copy it again','Delete everything'],1,'Duplicates should be identified and resolved according to the data rules.'],
['Which software is commonly used for tabular data?',['Spreadsheet software','Media player','Calculator only','Image viewer'],0,'Spreadsheet software is designed for structured rows, columns and calculations.'],
['Before submitting entered data, you should…',['Verify it','Close without checking','Change random values','Share it publicly'],0,'Verification catches errors before the record is submitted.'],
['What does data validation help with?',['Controlling allowed data','Increasing monitor brightness','Playing music','Charging devices'],0,'Validation can restrict entries to acceptable formats or values.']]},
{id:'it10-office-q2',class:'10th',trade:'IT-ITeS',unit:'Office Productivity',mode:'practice',time:0,questions:[
['Which spreadsheet function adds values?',['SUM','PRINT','MAIL','BOLD'],0,'SUM adds numeric values in a range.'],
['Rows in a spreadsheet are usually identified by…',['Numbers','Only symbols','Colours','Pictures'],0,'Rows are commonly numbered 1, 2, 3 and so on.'],
['A presentation is mainly made of…',['Slides','Rows only','Database tables only','Folders'],0,'Presentations are organised into slides.'],
['Which is a good document formatting practice?',['Consistent headings','Random fonts everywhere','Tiny unreadable text','No spacing'],0,'Consistent headings improve readability and structure.'],
['Sorting data means…',['Arranging records by a chosen field','Deleting all records','Printing the monitor','Changing passwords'],0,'Sorting arranges records according to a selected field or order.']]},
{id:'it11-spreadsheet-q1',class:'11th',trade:'IT-ITeS',unit:'Data & Spreadsheet Skills',mode:'timed',time:150,questions:[
['What does a cell reference identify?',['A spreadsheet cell','A printer','A web page','A folder'],0,'A cell reference such as A1 identifies a spreadsheet cell.'],
['Which symbol normally begins a spreadsheet formula?',['=','#','@','&'],0,'Spreadsheet formulas commonly begin with =.'],
['Filtering data is useful for…',['Showing matching records','Deleting formulas','Turning off the computer','Changing paper size'],0,'Filters display records that meet selected conditions.'],
['Which chart is useful for comparing categories?',['Bar/column chart','Password chart','Folder chart','Keyboard chart'],0,'Bar or column charts are useful for category comparisons.'],
['Data quality includes…',['Accuracy and consistency','Only colours','Screen size','Wallpaper'],0,'Good data should be accurate, consistent and complete enough for its purpose.']]},
{id:'it12-workplace-q1',class:'12th',trade:'IT-ITeS',unit:'Workplace Digital Skills',mode:'practice',time:0,questions:[
['A professional email subject should be…',['Clear and specific','Blank always','Only emojis','A password'],0,'A clear subject helps the recipient understand the purpose quickly.'],
['A resume should primarily show…',['Relevant skills and experience','Random jokes','Passwords','Unrelated advertisements'],0,'A resume presents relevant qualifications, skills and experience.'],
['Why are backups important?',['To recover data after loss','To slow computers','To remove keyboards','To change fonts'],0,'Backups provide a way to recover important data if the original is lost or damaged.'],
['What is a professional digital communication habit?',['Respectful and concise messages','Sharing confidential data publicly','Using insults','Ignoring context'],0,'Professional communication should be respectful, clear and appropriate.'],
['A portfolio is useful because it can…',['Show evidence of skills','Replace every exam','Store passwords publicly','Disable files'],0,'A portfolio provides evidence of projects, skills and completed work.']]},
{id:'ag9-foundation-q1',class:'9th',trade:'Agriculture',unit:'Agriculture Foundations',mode:'practice',time:0,questions:[
['What is soil important for?',['Plant growth','Only decoration','Charging phones','Printing'],0,'Soil provides support, water, air and nutrients needed by plants.'],
['Good quality seed generally helps with…',['Healthy crop establishment','Less sunlight','Broken tools','No germination'],0,'Good seed quality supports better germination and crop establishment.'],
['A farm tool should be used…',['Safely and correctly','Without care','As a toy','Only in rain'],0,'Correct and safe handling reduces risk and improves work quality.'],
['Nursery work mainly involves…',['Raising young plants','Making computers','Printing reports','Repairing phones'],0,'A nursery is used to raise and care for young plants before further planting.'],
['Field observation should be…',['Recorded carefully','Guessed later','Deleted immediately','Hidden'],0,'Careful observation and records support learning and decision-making.']]},
{id:'ag10-crops-q1',class:'10th',trade:'Agriculture',unit:'Crop Production',mode:'timed',time:120,questions:[
['Crop planning should consider…',['Season and crop needs','Only colour','Mobile battery','Keyboard type'],0,'Season, climate and crop requirements are important planning factors.'],
['Irrigation means…',['Supplying water to crops','Removing all soil','Harvesting computers','Packing books'],0,'Irrigation supplies water when natural rainfall is insufficient.'],
['Nursery beds are used to…',['Raise seedlings','Store computers','Print labels only','Charge tools'],0,'Nursery beds provide a suitable place for raising seedlings.'],
['Plant nutrition refers to…',['Nutrient needs of plants','Phone settings','Book binding','Internet speed'],0,'Plants require essential nutrients for growth and development.'],
['Crop protection begins with…',['Regular observation','Ignoring symptoms','Random spraying','Removing all plants'],0,'Observation helps identify problems and choose appropriate management.']]},
{id:'ag11-floriculture-q1',class:'11th',trade:'Agriculture',unit:'Floriculture & Nursery',mode:'practice',time:0,questions:[
['Floriculture is mainly concerned with…',['Flower and ornamental crops','Computer networks','Data entry','Road construction'],0,'Floriculture focuses on cultivation and management of flowers and ornamental plants.'],
['Propagation means…',['Producing new plants','Harvesting data','Printing documents','Sorting files'],0,'Plant propagation is the process of producing new plants.'],
['Nursery sanitation helps reduce…',['Pest and disease risks','Keyboard errors','Paper size','Internet cost'],0,'Clean nursery practices can reduce disease and pest problems.'],
['Flowers should be harvested at the…',['Appropriate stage for the intended use','Random time','End of the year only','After drying completely'],0,'Harvest stage affects flower quality and shelf life.'],
['Plant care can include…',['Watering and nutrition','Password sharing','File deletion','Screen brightness'],0,'Watering and nutrition are basic parts of plant care.']]},
{id:'ag12-enterprise-q1',class:'12th',trade:'Agriculture',unit:'Applied Agriculture & Enterprise',mode:'timed',time:150,questions:[
['Farm records help track…',['Inputs, activities and outputs','Only weather emojis','Passwords','Computer games'],0,'Records help track farm inputs, activities, outputs and costs.'],
['A simple enterprise plan should include…',['Activities and costs','Only a logo','No records','Random numbers'],0,'Planning needs activities, resources and expected costs/revenue considerations.'],
['Post-harvest handling aims to…',['Maintain quality and reduce losses','Increase damage','Hide produce','Stop all storage'],0,'Proper handling helps maintain quality and reduce post-harvest losses.'],
['An agriculture enterprise is…',['A planned agriculture-related economic activity','Only a classroom game','A keyboard shortcut','A browser'],0,'An enterprise is an organised activity intended to create useful output/value.'],
['A project presentation should include…',['Objective, work and findings','Only a title','Passwords','Unrelated jokes'],0,'A good presentation explains what was planned, done and learned.']]}
];
const customKey='sandipani_quiz_custom_v1', histKey='sandipani_quiz_history_v1';
let custom=JSON.parse(localStorage.getItem(customKey)||'[]'), history=JSON.parse(localStorage.getItem(histKey)||'[]');
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const all=()=>[...BUILTIN,...custom];
function saveHist(){localStorage.setItem(histKey,JSON.stringify(history));renderStats();renderHistory();}
function stats(){const a=history.map(x=>x.pct);return {attempts:a.length,best:a.length?Math.max(...a):0,avg:a.length?Math.round(a.reduce((s,n)=>s+n,0)/a.length):0,passed:history.filter(x=>x.passed).length};}
function renderStats(){const s=stats();$('heroAttempts').textContent=s.attempts;$('heroBest').textContent=s.best+'%';$('heroAvg').textContent=s.avg+'%';$('heroPassed').textContent=s.passed;}
function filtered(){const q=$('quizSearch').value.trim().toLowerCase(), c=$('quizClass').value,t=$('quizTrade').value,m=$('quizMode').value;return all().filter(x=>(c==='all'||x.class===c)&&(t==='all'||x.trade===t)&&(m==='all'||x.mode===m)&&(!q||[x.unit,x.trade,x.class,...x.questions.map(z=>z[0])].join(' ').toLowerCase().includes(q)));}
function renderCatalog(){const list=filtered();$('quizGrid').innerHTML=list.map(x=>`<article class="quiz-card"><div class="quiz-card-top"><span class="qtrade">${x.trade==='IT-ITeS'?'💻':'🌱'} ${esc(x.trade)}</span><span class="qmode ${x.mode}">${x.mode==='timed'?'⏱ Timed':'✓ Practice'}</span></div><div class="qclass">Class ${esc(x.class)} • ${x.questions.length} questions</div><h3>${esc(x.unit)}</h3><p>Unit assessment with instant score, answer review and retry.</p><div class="qcard-meta"><span>${x.time?Math.ceil(x.time/60)+' min':'Self paced'}</span><span>🎯 '+(x.questions.length*20)+' marks</span><span>✓ 50% pass</span></div><button class="q-start" data-start="${esc(x.id)}">Start Quiz →</button></article>`).join('');$('quizEmpty').classList.toggle('hidden',!!list.length);document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>startQuiz(b.dataset.start));}
let active=null,answers=[],idx=0,timer=null,seconds=0,startedAt=0;
function startQuiz(id){const q=all().find(x=>x.id===id);if(!q)return;active=q;answers=Array(q.questions.length).fill(null);idx=0;seconds=q.time||0;startedAt=Date.now();openModal();renderQuestion();if(timer)clearInterval(timer);if(seconds){timer=setInterval(()=>{seconds--;updateTimer();if(seconds<=0){clearInterval(timer);finishQuiz(true);}},1000);}}
function openModal(){ $('quizModal').classList.remove('hidden'); }
function closeModal(){if(timer)clearInterval(timer);$('quizModal').classList.add('hidden');}
function updateTimer(){const e=$('quizTimer');if(e)e.textContent=Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');}
function renderQuestion(){const q=active.questions[idx], chosen=answers[idx];$('quizBody').innerHTML=`<div class="attempt-head"><div><span class="q-kicker">${esc(active.trade)} • CLASS ${esc(active.class)}</span><h2>${esc(active.unit)}</h2></div><div class="timer ${seconds<=30&&seconds?'urgent':''}" id="quizTimer">${seconds?Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0'):'Practice'}</div></div><div class="attempt-progress"><span>Question ${idx+1} of ${active.questions.length}</span><div><i style="width:${((idx+1)/active.questions.length)*100}%"></i></div></div><div class="q-question"><div class="q-number">Q${idx+1}</div><h3>${esc(q[0])}</h3><div class="options">${q[1].map((o,i)=>`<button class="option ${chosen===i?'selected':''}" data-opt="${i}"><span>${String.fromCharCode(65+i)}</span>${esc(o)}</button>`).join('')}</div></div><div class="attempt-footer"><button class="q-btn ghost small" id="quitQuiz">Quit</button><div><button class="q-btn ghost small" id="prevQ" ${idx===0?'disabled':''}>← Previous</button><button class="q-btn primary small" id="nextQ">${idx===active.questions.length-1?'Submit Quiz':'Next →'}</button></div></div>`;document.querySelectorAll('[data-opt]').forEach(b=>b.onclick=()=>{answers[idx]=Number(b.dataset.opt);renderQuestion();});$('prevQ').onclick=()=>{if(idx>0){idx--;renderQuestion();}};$('nextQ').onclick=()=>{if(answers[idx]===null){alert('Please select an answer first.');return;}if(idx<active.questions.length-1){idx++;renderQuestion();}else finishQuiz(false);};$('quitQuiz').onclick=()=>{if(confirm('Exit this quiz? Your current attempt will not be saved.'))closeModal();};}
function finishQuiz(auto){if(timer)clearInterval(timer);let correct=0;active.questions.forEach((q,i)=>{if(answers[i]===q[2])correct++;});const pct=Math.round(correct/active.questions.length*100), item={id:Date.now(),quiz:active.unit,class:active.class,trade:active.trade,correct,total:active.questions.length,pct,passed:pct>=50,date:new Date().toLocaleString('en-IN'),duration:Math.max(1,Math.round((Date.now()-startedAt)/1000))};history.unshift(item);history=history.slice(0,50);saveHist();$('quizBody').innerHTML=`<div class="result-head"><div class="result-circle"><strong>${pct}%</strong><span>${pct>=80?'Great work!':pct>=50?'Passed':'Keep practising'}</span></div><div><span class="q-kicker">${auto?'TIME UP • ':''}RESULT</span><h2>${esc(active.unit)}</h2><p>${correct} correct out of ${active.questions.length} • ${pct>=50?'Pass':'Practice required'}</p></div></div><div class="result-stats"><div><b>${correct}</b><span>Correct</span></div><div><b>${active.questions.length-correct}</b><span>Incorrect</span></div><div><b>${pct}%</b><span>Score</span></div><div><b>${Math.round(item.duration/60)}m</b><span>Time</span></div></div><div class="review-list"><h3>Answer Review</h3>${active.questions.map((q,i)=>`<div class="review ${answers[i]===q[2]?'ok':'bad'}"><b>Q${i+1}. ${esc(q[0])}</b><span>Your answer: ${answers[i]===null?'Not answered':esc(q[1][answers[i]])}</span><span>Correct: ${esc(q[1][q[2]])}</span><small>${esc(q[3])}</small></div>`).join('')}</div><div class="result-actions"><button class="q-btn ghost" id="closeResult">Close</button><button class="q-btn primary" id="retryResult">Retry Quiz</button></div>`;$('retryResult').onclick=()=>startQuiz(active.id);$('closeResult').onclick=closeModal;}
function renderHistory(){if(!history.length){$('historyGrid').innerHTML='<div class="history-empty">📊<b>No quiz attempts yet</b><span>Complete a quiz and your score will appear here.</span></div>';return;}$('historyGrid').innerHTML=history.slice(0,12).map(x=>`<div class="history-card"><div class="history-score ${x.passed?'pass':'fail'}">${x.pct}%</div><div><b>${esc(x.quiz)}</b><span>${esc(x.class)} • ${esc(x.trade)} • ${x.correct}/${x.total} correct</span><small>${esc(x.date)}</small></div><em>${x.passed?'PASSED':'PRACTICE'}</em></div>`).join('');}
function filters(){renderCatalog();}
$('quizSearch').oninput=filters;$('quizClass').onchange=filters;$('quizTrade').onchange=filters;$('quizMode').onchange=filters;$('resetQuizFilters').onclick=()=>{$('quizSearch').value='';$('quizClass').value='all';$('quizTrade').value='all';$('quizMode').value='all';renderCatalog();};$('historyBtn').onclick=()=>$('history').scrollIntoView({behavior:'smooth'});$('clearHistory').onclick=()=>{if(confirm('Clear all quiz history from this device?')){history=[];saveHist();}};document.querySelectorAll('[data-close]').forEach(x=>x.onclick=closeModal);$('quizMenu').onclick=()=>document.querySelector('.quiz-nav nav').classList.toggle('open');
renderCatalog();renderStats();renderHistory();
(async function loadCentralQuiz(){try{if(typeof API!=='undefined'){const r=await API.getQuizPublic();const qs=(r&&r.questions)||[];const grouped={};qs.forEach(x=>{const key=String(x.Class)+'|'+String(x.Trade)+'|'+String(x.Unit);(grouped[key]||(grouped[key]=[])).push([String(x.Question),[String(x['Option A']),String(x['Option B']),String(x['Option C']),String(x['Option D'])],Number(x.Correct)||0,String(x.Explanation||'')]);});Object.keys(grouped).forEach(k=>{const [cls,trade,unit]=k.split('|'),sample=qs.find(x=>String(x.Class)+'|'+String(x.Trade)+'|'+String(x.Unit)===k);BUILTIN=[...BUILTIN.filter(q=>q.id!=='central-'+k),{id:'central-'+k,class:cls,trade,unit,mode:String(sample.Mode||'practice'),time:Number(sample.Time)||0,questions:grouped[k]}];});renderCatalog();renderStats();}}catch(e){console.warn('Central Quiz unavailable; using built-in bank.',e)}})();
})();
