let adminPin='', records=[], settingsCache=[], configCache={};
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function msg(t,type='info'){const e=$('adminMessage');e.textContent=t;e.className='message '+type;e.style.display='block';}
async function adminLogin(){const pin=$('adminPin').value.trim();if(!pin)return msg('Enter Admin PIN.','error');try{const r=await API.verifyAdmin(pin);if(!r.valid)return msg('Invalid Admin PIN.','error');adminPin=pin;$('loginCard').classList.add('hidden');$('adminPanel').classList.remove('hidden');await refreshAll();msg('Admin login successful.','success');}catch(e){msg(e.message,'error');}}
function logout(){adminPin='';$('adminPanel').classList.add('hidden');$('loginCard').classList.remove('hidden');}
function filters(){return { 'Academic Year':$('fYear').value,'Class':$('fClass').value,'Section':$('fSection').value,'Gender':$('fGender').value,'Stream':$('fStream').value,'IT Subject in Place of This Language':$('fIT').value,search:$('studentSearch').value.trim()};}
async function refreshAll(){await Promise.all([loadDashboard(),loadStudents(),loadSettings(),loadConfig(),loadGalleryAdmin()]);}
async function loadDashboard(){const s=await API.getStats(adminPin,filters());$('statStudents').textContent=s.total;$('c9').textContent=s.classes['9th'];$('c10').textContent=s.classes['10th'];$('c11').textContent=s.classes['11th'];$('c12').textContent=s.classes['12th'];$('gMale').textContent=s.gender.Male;$('gFemale').textContent=s.gender.Female;$('gOther').textContent=s.gender.Other;$('itHindi').textContent=s.it.Hindi;$('itEnglish').textContent=s.it.English;$('itBoth').textContent=s.it['Hindi & English'];$('aHindi').textContent=s.additional.Hindi;$('aEnglish').textContent=s.additional.English;$('aMath').textContent=s.additional.Mathematics;$('aBio').textContent=s.additional.Biology;$('aSkipHindi').textContent=s.additional['Completely Skipped Hindi'];$('aSkipEnglish').textContent=s.additional['Completely Skipped English'];$('sMath').textContent=s.stream.Mathematics;$('sBio').textContent=s.stream.Biology;$('sArts').textContent=s.stream.Arts;$('sCommerce').textContent=s.stream.Commerce;$('jDDEO').textContent=s.jobRole['Domestic Data Entry Operator'];$('jWeb').textContent=s.jobRole['Web Developer'];$('statDeleted').textContent=s.meta.deleted;$('statFields').textContent=s.meta.fields;}
async function loadStudents(){records=await API.getStudents(adminPin,filters());$('studentCount').textContent=records.length+' record(s)';$('studentRows').innerHTML=records.length?records.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r['Academic Year'])}</td><td>${esc(r.Class)}</td><td>${esc(r.Section)}</td><td>${esc(r['Roll Number']||'—')}</td><td>${esc(r['Student Name'])}</td><td>${esc(r["Father's Name"])}</td><td>${esc(r.Medium)}</td><td>${esc(r.Gender)}</td><td>${esc(r['Mobile Number'])}</td><td>${esc(r['Samagra ID'])}</td><td>${esc(r.Trade)}</td><td>${esc(r['Job Role'])}</td><td>${esc(r.Stream||'—')}</td><td>${esc(r['IT Subject in Place of This Language'])}</td><td>${esc(r['Additional Subject'])}</td><td><button class="mini" onclick="viewStudent(${r._row})">View</button> <button class="mini" onclick="editStudent(${r._row})">Edit</button> <button class="mini danger" onclick="deleteStudent(${r._row})">Delete</button></td></tr>`).join(''):'<tr><td colspan="17">No student records found.</td></tr>';}
function clearFilters(){['fYear','fClass','fSection','fGender','fStream','fIT','studentSearch'].forEach(id=>$(id).value='');applyFilters();}
async function applyFilters(){try{await Promise.all([loadStudents(),loadDashboard()]);}catch(e){msg(e.message,'error');}}
function optionsHtml(arr,selected=''){return (arr||[]).map(x=>`<option value="${esc(x)}" ${String(x)===String(selected)?'selected':''}>${esc(x)}</option>`).join('');}
function editForm(r){return `<div class="grid edit-grid"><div class="field"><label>Academic Year</label><select id="eYear">${optionsHtml(configCache.academicYears,r['Academic Year'])}</select></div><div class="field"><label>Class</label><select id="eClass"><option>9th</option><option>10th</option><option>11th</option><option>12th</option></select></div><div class="field"><label>Section</label><select id="eSection">${optionsHtml(configCache.sections,r.Section)}</select></div><div class="field"><label>Roll Number <small>(Admin will allot later)</small></label><input id="eRoll" inputmode="numeric" maxlength="6" value="${esc(r['Roll Number']||'')}"><div class="hint">Leave blank until roll number is allotted.</div></div><div class="field"><label>Student Name</label><input id="eName" value="${esc(r['Student Name'])}"></div><div class="field"><label>Father's Name</label><input id="eFather" value="${esc(r["Father's Name"])}"></div><div class="field"><label>Medium</label><select id="eMedium"><option ${r.Medium==='Hindi'?'selected':''}>Hindi</option><option ${r.Medium==='English'?'selected':''}>English</option></select></div><div class="field"><label>Gender</label><select id="eGender"><option>Male</option><option>Female</option><option>Other</option></select></div><div class="field"><label>Mobile Number</label><input id="eMobile" maxlength="10" value="${esc(r['Mobile Number'])}"></div><div class="field"><label>Samagra ID</label><input id="eSamagra" maxlength="9" value="${esc(r['Samagra ID'])}"></div><div class="field"><label>Trade</label><input value="IT-ITeS" readonly></div><div class="field"><label>Job Role</label><input id="eJob" readonly></div><div class="field" id="eStreamWrap"><label>Stream</label><select id="eStream"><option value="">Select Stream</option>${optionsHtml(['Mathematics','Biology','Arts','Commerce'],r.Stream)}</select></div><div class="field"><label>IT Subject in Place of This Language</label><select id="eIT">${optionsHtml(configCache.itReplacement,r['IT Subject in Place of This Language'])}</select></div><div class="field"><label>Additional Subject / Language Status</label><select id="eAdditional">${optionsHtml(configCache.additionalSubjects,r['Additional Subject'])}</select></div></div>`;}
function setEditClass(){const c=$('eClass').value;$('eJob').value=['9th','10th'].includes(c)?'Domestic Data Entry Operator':'Web Developer';$('eStreamWrap').style.display=['11th','12th'].includes(c)?'':'none';$('eStream').required=['11th','12th'].includes(c);}
function modal(title,body,buttons=''){const old=$('modal');if(old)old.remove();document.body.insertAdjacentHTML('beforeend',`<div id="modal" class="modal"><div class="modal-card"><div class="modal-head"><h2>${title}</h2><button class="mini" onclick="closeModal()">✕</button></div><div>${body}</div>${buttons?`<div class="modal-actions">${buttons}</div>`:''}</div></div>`);}
function closeModal(){$('modal')?.remove();}
function findRow(row){return records.find(x=>Number(x._row)===Number(row));}
function viewStudent(row){const r=findRow(row);if(!r)return;const fields=['Academic Year','Class','Section','Roll Number','Student Name',"Father's Name",'Medium','Gender','Mobile Number','Samagra ID','Trade','Job Role','Stream','IT Subject in Place of This Language','Additional Subject'];modal('Student Details','<div class="detail-grid">'+fields.map(k=>`<div><small>${esc(k)}</small><b>${esc(r[k]||'—')}</b></div>`).join('')+'</div>','<button class="btn secondary" onclick="closeModal()">Close</button>');}
function editStudent(row){const r=findRow(row);if(!r)return;modal('Edit Student',editForm(r),'<button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveEdit('+row+')">Save Changes</button>');$('eClass').value=r.Class;$('eGender').value=r.Gender;$('eClass').addEventListener('change',setEditClass);setEditClass();}
async function saveEdit(row){const d={'Academic Year':$('eYear').value,Class:$('eClass').value,Section:$('eSection').value,'Roll Number':$('eRoll').value.trim(),'Student Name':$('eName').value.trim(),"Father's Name":$('eFather').value.trim(),Medium:$('eMedium').value,Gender:$('eGender').value,'Mobile Number':$('eMobile').value.trim(),'Samagra ID':$('eSamagra').value.trim(),Trade:'IT-ITeS','Job Role':$('eJob').value,Stream:['11th','12th'].includes($('eClass').value)?$('eStream').value:'','IT Subject in Place of This Language':$('eIT').value,'Additional Subject':$('eAdditional').value};try{await API.updateStudent(adminPin,row,d);closeModal();msg('Student updated successfully.','success');await applyFilters();}catch(e){msg(e.message,'error');}}
async function deleteStudent(row){const r=findRow(row);if(!r)return;if(!confirm(`Delete ${r['Student Name']}? This record will move to Deleted Records.`))return;try{await API.deleteStudent(adminPin,row);msg('Student deleted.','success');await applyFilters();await loadDeleted();}catch(e){msg(e.message,'error');}}
async function loadDeleted(){const d=await API.getDeleted(adminPin);$('deletedRows').innerHTML=d.length?d.map(x=>`<tr><td>${esc(x.deletedAt)}</td><td>${esc(x.type)}</td><td><button class="mini" onclick="restoreRecord(${x.row})">Restore</button></td></tr>`).join(''):'<tr><td colspan="3">No deleted records.</td></tr>';}
async function restoreRecord(row){if(!confirm('Restore this student record?'))return;try{await API.restoreDeleted(adminPin,row);msg('Record restored.','success');await refreshAll();await loadDeleted();}catch(e){msg(e.message,'error');}}
function csvEscape(v){return '"'+String(v??'').replace(/"/g,'""')+'"';}
function exportCSV(){const cols=['Academic Year','Class','Section','Roll Number','Student Name',"Father's Name",'Medium','Gender','Mobile Number','Samagra ID','Trade','Job Role','Stream','IT Subject in Place of This Language','Additional Subject'];const csv=[cols,...records.map(r=>cols.map(c=>r[c]||''))].map(row=>row.map(csvEscape).join(',')).join('\r\n');downloadBlob(csv,'vocational-student-records.csv','text/csv;charset=utf-8');}
function exportExcel(){const cols=['Sr. No.','Academic Year','Class','Section','Roll Number','Student Name',"Father's Name",'Medium','Gender','Mobile Number','Samagra ID','Trade','Job Role','Stream','IT Subject in Place of This Language','Additional Subject'];const rows=records.map((r,i)=>[i+1,...cols.slice(1).map(c=>r[c]||'')]);const html='<html><head><meta charset="UTF-8"></head><body><table border="1"><tr>'+cols.map(c=>`<th>${esc(c)}</th>`).join('')+'</tr>'+rows.map(row=>'<tr>'+row.map(c=>`<td>${esc(c)}</td>`).join('')+'</tr>').join('')+'</table></body></html>';downloadBlob(html,'vocational-student-records.xls','application/vnd.ms-excel');}
function downloadBlob(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function printReport(){const w=window.open('','_blank');w.document.write('<html><head><title>Vocational Student Report</title><style>body{font-family:Arial}table{border-collapse:collapse;width:100%;font-size:11px}th,td{border:1px solid #777;padding:5px}th{background:#eee}</style></head><body><h2>Vocational Student Record Report</h2><table><tr>'+['Sr. No.','Academic Year','Class','Section','Roll Number','Student Name',"Father's Name",'Medium','Gender','Mobile Number','Samagra ID','Trade','Job Role','Stream','IT Subject in Place of This Language','Additional Subject'].map(c=>`<th>${esc(c)}</th>`).join('')+'</tr>'+records.map((r,i)=>'<tr>'+[i+1,'Academic Year','Class','Section','Roll Number','Student Name',"Father's Name",'Medium','Gender','Mobile Number','Samagra ID','Trade','Job Role','Stream','IT Subject in Place of This Language','Additional Subject'].map((c,j)=>`<td>${esc(j===0?i+1:r[c]||'—')}</td>`).join('')+'</tr>').join('')+'</table><script>window.print();</script></body></html>');w.document.close();}
function fieldRow(f,i){return `<div class="builder-row" data-index="${i}"><input class="sf-name" value="${esc(f.field)}" ${f.system?'readonly':''}><select class="sf-type"><option value="text" ${f.type==='text'?'selected':''}>text</option><option value="dropdown" ${f.type==='dropdown'?'selected':''}>dropdown</option><option value="tel" ${f.type==='tel'?'selected':''}>tel</option><option value="number" ${f.type==='number'?'selected':''}>number</option></select><input class="sf-options" placeholder="Options separated by |" value="${esc(f.options)}"><select class="sf-required"><option value="Yes" ${f.required?'selected':''}>Required</option><option value="No" ${!f.required?'selected':''}>Optional</option></select><input class="sf-classes" placeholder="All or 9th|10th" value="${esc(f.onlyClasses||'All')}"><input class="sf-section" placeholder="Section" value="${esc(f.section||'Custom')}"><label><input class="sf-enabled" type="checkbox" ${f.enabled?'checked':''}> On</label><button class="mini danger" onclick="removeField(${i})">Delete</button></div>`;}
function renderBuilder(){$('builder').innerHTML=settingsCache.map(fieldRow).join('');}
async function loadSettings(){settingsCache=await API.getSettings();renderBuilder();}
async function loadConfig(){configCache=await API.getConfig();$('fYear').innerHTML='<option value="">All Academic Years</option>'+optionsHtml(configCache.academicYears);$('fSection').innerHTML='<option value="">All Sections</option>'+optionsHtml(configCache.sections);}
function addField(){settingsCache.push({field:'New Custom Field',type:'text',options:'',required:false,enabled:true,onlyClasses:'All',system:false,section:'Custom'});renderBuilder();}
function removeField(i){if(settingsCache[i].system)return alert('Core field cannot be deleted.');settingsCache.splice(i,1);renderBuilder();}
async function saveSettings(){const rows=[...document.querySelectorAll('.builder-row')];const next=rows.map((r,i)=>({...settingsCache[i],field:r.querySelector('.sf-name').value.trim(),type:r.querySelector('.sf-type').value,options:r.querySelector('.sf-options').value,required:r.querySelector('.sf-required').value==='Yes',onlyClasses:r.querySelector('.sf-classes').value||'All',section:r.querySelector('.sf-section').value||'Custom',enabled:r.querySelector('.sf-enabled').checked}));try{settingsCache=await API.saveSettings(adminPin,next);renderBuilder();msg('Form Builder saved.','success');}catch(e){msg(e.message,'error');}}
async function saveConfig(){const cfg={academicYears:$('cfgYears').value.split(/[,\n|]+/).map(x=>x.trim()).filter(Boolean),sections:$('cfgSections').value.split(/[,\n|]+/).map(x=>x.trim()).filter(Boolean),itReplacement:configCache.itReplacement,additionalSubjects:configCache.additionalSubjects};try{configCache=await API.saveConfig(adminPin,cfg);await loadConfig();msg('Academic years and sections saved.','success');}catch(e){msg(e.message,'error');}}
function showTab(tab){document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('hidden',x.id!=='panel-'+tab));if(tab==='deleted')loadDeleted();if(tab==='settings'){loadSettings();$('cfgYears').value=(configCache.academicYears||[]).join(', ');$('cfgSections').value=(configCache.sections||[]).join(', ');}}
function saveApiUrl(){const v=$('apiUrl').value.trim();localStorage.setItem('sandipani_api_url',v);msg('API URL saved in this browser. For all users, update js/config.js too.','success');}
async function setupInfo(){try{const d=await API.call('setup');$('setupInfo').innerHTML='<b>Google Sheet:</b> <a target="_blank" href="'+esc(d.sheetUrl)+'">Open Sheet</a>'; }catch(e){$('setupInfo').textContent=e.message;}}
document.addEventListener('DOMContentLoaded',()=>{$('adminPin')?.addEventListener('keydown',e=>{if(e.key==='Enter')adminLogin();});$('apiUrl').value=localStorage.getItem('sandipani_api_url')||DEFAULT_API_URL;});

async function loadGalleryAdmin(){
  const rows=await API.getGallery();
  const labels={guest:'Guest Lectures',industrial:'Industrial Visit',classroom:'Class Room Teaching',activities:'Student Activities'};
  const box=$('galleryAdminRows'); if(!box)return;
  box.innerHTML=(rows||[]).map(x=>`<tr><td>${esc(labels[x.section]||x.section)}</td><td>${esc(x.title)}</td><td><img src="${esc(x.thumbnailUrl||x.url)}" style="width:90px;height:60px;object-fit:cover;border-radius:8px"></td><td><button class="mini danger" onclick="deleteGalleryPhoto('${esc(x.id)}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="4">No uploaded photos yet.</td></tr>';
}
async function uploadGalleryPhoto(){
  const file=$('galleryFile')?.files?.[0], section=$('gallerySection')?.value, title=$('galleryTitle')?.value.trim(), status=$('galleryUploadStatus');
  if(!file)return msg('Select a photo first.','error');
  if(!title)return msg('Enter a photo title.','error');
  if(!['image/jpeg','image/png','image/webp'].includes(file.type))return msg('Only JPG, PNG or WebP images are allowed.','error');
  status.textContent='Preparing photo…';status.className='message';status.style.display='block';
  try{
    const prepared=await prepareGalleryImage_(file);
    await API.uploadGallery(adminPin,{section,title,name:prepared.name,mimeType:prepared.mimeType,base64:prepared.base64});
    status.textContent='Photo uploaded successfully.';status.className='message success';
    $('galleryFile').value='';$('galleryTitle').value='';await loadGalleryAdmin();
  }catch(e){status.textContent=e.message||'Photo upload failed.';status.className='message error';}
}
function prepareGalleryImage_(file){
  return new Promise((resolve,reject)=>{
    const img=new Image(), url=URL.createObjectURL(file);
    img.onload=()=>{
      try{
        const maxSide=1800, scale=Math.min(1,maxSide/Math.max(img.naturalWidth,img.naturalHeight));
        const w=Math.max(1,Math.round(img.naturalWidth*scale)), h=Math.max(1,Math.round(img.naturalHeight*scale));
        const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;
        canvas.getContext('2d').drawImage(img,0,0,w,h);
        const make=q=>{
          const dataUrl=canvas.toDataURL('image/jpeg',q), b64=dataUrl.split(',')[1]||'';
          if(b64.length<=2200000 || q<=0.55){
            URL.revokeObjectURL(url);
            resolve({name:(file.name.replace(/\.[^.]+$/,'')||'gallery')+'.jpg',mimeType:'image/jpeg',base64:b64});
          }else make(q-0.08);
        };
        make(0.82);
      }catch(err){URL.revokeObjectURL(url);reject(err);}
    };
    img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Could not read the selected image.'));};
    img.src=url;
  });
}
async function deleteGalleryPhoto(id){if(!confirm('Delete this gallery photo?'))return;try{await API.deleteGallery(adminPin,id);msg('Gallery photo deleted.','success');await loadGalleryAdmin();}catch(e){msg(e.message,'error');}}
