let adminPin='', records=[], settingsCache=[], configCache={};
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function msg(t,type='info'){const e=$('adminMessage');e.textContent=t;e.className='message '+type;e.style.display='block';}
function adminUnlockUI(on){let e=$('adminUnlockOverlay');if(on){if(!e){document.body.insertAdjacentHTML('beforeend','<div id="adminUnlockOverlay" style="position:fixed;inset:0;background:rgba(248,250,252,.96);z-index:100000;display:flex;align-items:center;justify-content:center;padding:20px;text-align:center"><div style="background:#fff;border:1px solid #e4e7ec;border-radius:16px;padding:28px;max-width:380px;width:100%;box-shadow:0 18px 50px rgba(15,23,42,.12)"><div style="font-size:42px">🔐</div><h2 style="margin:10px 0 6px">Unlocking Admin Panel…</h2><p style="margin:0;color:#667085">PIN verified. Loading secure admin data. Please wait.</p><div style="height:5px;background:#e5e7eb;border-radius:99px;overflow:hidden;margin-top:18px"><i style="display:block;width:45%;height:100%;background:#0b4fa3;border-radius:99px;animation:sandipaniUnlock 1.1s ease-in-out infinite"></i></div></div></div><style>@keyframes sandipaniUnlock{0%{transform:translateX(-120%)}100%{transform:translateX(240%)}}</style>');}}else{e=$('adminUnlockOverlay');if(e)e.remove();}}
async function adminLogin(){const pin=$('adminPin').value.trim();if(!pin)return msg('Enter Admin PIN.','error');adminUnlockUI(true);try{const r=await API.verifyAdmin(pin);if(!r.valid){adminUnlockUI(false);return msg('Invalid Admin PIN.','error');}adminPin=pin;if(window.AdminAuth&&AdminAuth.set)AdminAuth.set(pin,Date.now()+5*60*60*1000);await refreshAll();$('loginCard').classList.add('hidden');$('connectionCard')?.classList.remove('hidden');$('adminPanel').classList.remove('hidden');adminUnlockUI(false);msg('Admin login successful.','success');}catch(e){adminUnlockUI(false);msg(e.message||'Unable to unlock Admin Panel.','error');}}
function logout(){adminPin='';if(window.AdminAuth&&AdminAuth.clear)AdminAuth.clear();$('adminPanel').classList.add('hidden');$('loginCard').classList.remove('hidden');}
function filters(){return { 'Academic Year':$('fYear').value,'Class':$('fClass').value,'Section':$('fSection').value,'Gender':$('fGender').value,'Stream':$('fStream').value,'IT Subject in Place of This Language':$('fIT').value,search:$('studentSearch').value.trim()};}
async function refreshAll(){await Promise.all([loadDashboard(),loadStudents(),loadSettings(),loadConfig(),loadGalleryAdmin()]);}
async function loadDashboard(){const s=await API.getStats(adminPin,filters());$('statStudents').textContent=s.total;$('c9').textContent=s.classes['9th'];$('c10').textContent=s.classes['10th'];$('c11').textContent=s.classes['11th'];$('c12').textContent=s.classes['12th'];$('gMale').textContent=s.gender.Male;$('gFemale').textContent=s.gender.Female;$('gOther').textContent=s.gender.Other;$('itHindi').textContent=s.it.Hindi;$('itEnglish').textContent=s.it.English;$('itBoth').textContent=s.it['Hindi & English'];$('aHindi').textContent=s.additional.Hindi;$('aEnglish').textContent=s.additional.English;$('aMath').textContent=s.additional.Mathematics;$('aBio').textContent=s.additional.Biology;$('aSkipHindi').textContent=s.additional['Completely Skipped Hindi'];$('aSkipEnglish').textContent=s.additional['Completely Skipped English'];$('sMath').textContent=s.stream.Mathematics;$('sBio').textContent=s.stream.Biology;$('sArts').textContent=s.stream.Arts;$('sCommerce').textContent=s.stream.Commerce;$('jDDEO').textContent=s.jobRole['Domestic Data Entry Operator'];$('jWeb').textContent=s.jobRole['Web Developer'];$('statDeleted').textContent=s.meta.deleted;$('statFields').textContent=s.meta.fields;}
async function loadStudents(){records=await API.getStudents(adminPin,filters());$('studentCount').textContent=records.length+' record(s)';$('studentRows').innerHTML=records.length?records.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r['Academic Year'])}</td><td>${esc(r.Class)}</td><td>${esc(r.Section)}</td><td>${esc(r['Roll Number']||'—')}</td><td>${esc(r['Student Name'])}</td><td>${esc(r["Father's Name"])}</td><td>${esc(r.Medium)}</td><td>${esc(r.Gender)}</td><td>${esc(r['Mobile Number'])}</td><td>${esc(r['Samagra ID'])}</td><td>${esc(r.Trade)}</td><td>${esc(r['Job Role'])}</td><td>${esc(r.Stream||'—')}</td><td>${esc(r['IT Subject in Place of This Language'])}</td><td>${esc(r['Additional Subject'])}</td><td><button class="mini" onclick="viewStudent(${r._row})">View</button> <button class="mini" onclick="editStudent(${r._row})">Edit</button> <button class="mini danger" onclick="deleteStudent(${r._row})">Delete</button></td></tr>`).join(''):'<tr><td colspan="17">No student records found.</td></tr>';}
function clearFilters(){['fYear','fClass','fSection','fGender','fStream','fIT','studentSearch'].forEach(id=>$(id).value='');applyFilters();}
async function applyFilters(){try{await Promise.all([loadStudents(),loadDashboard()]);}catch(e){msg(e.message,'error');}}
function optionsHtml(arr,selected=''){return (arr||[]).map(x=>`<option value="${esc(x)}" ${String(x)===String(selected)?'selected':''}>${esc(x)}</option>`).join('');}
function editForm(r){return `<div class="grid edit-grid"><div class="field"><label>Academic Year</label><select id="eYear">${optionsHtml(configCache.academicYears,r['Academic Year'])}</select></div><div class="field"><label>Class</label><select id="eClass"><option>9th</option><option>10th</option><option>11th</option><option>12th</option></select></div><div class="field"><label>Section</label><select id="eSection">${optionsHtml(configCache.sections,r.Section)}</select></div><div class="field"><label>Roll Number <small>(Admin will allot later)</small></label><input id="eRoll" inputmode="numeric" maxlength="6" value="${esc(r['Roll Number']||'')}"><div class="hint">Leave blank until roll number is allotted.</div></div><div class="field"><label>Student Name</label><input id="eName" value="${esc(r['Student Name'])}"></div><div class="field"><label>Father's Name</label><input id="eFather" value="${esc(r["Father's Name"])}"></div><div class="field"><label>Medium</label><select id="eMedium"><option ${r.Medium==='Hindi'?'selected':''}>Hindi</option><option ${r.Medium==='English'?'selected':''}>English</option></select></div><div class="field"><label>Gender</label><select id="eGender"><option>Male</option><option>Female</option><option>Other</option></select></div><div class="field"><label>Mobile Number</label><input id="eMobile" maxlength="10" value="${esc(r['Mobile Number'])}"></div><div class="field"><label>Samagra ID</label><input id="eSamagra" maxlength="9" value="${esc(r['Samagra ID'])}"></div><div class="field"><label>Trade</label><input value="IT-ITeS" readonly></div><div class="field"><label>Job Role</label><input id="eJob" readonly></div><div class="field" id="eStreamWrap"><label>Stream</label><select id="eStream"><option value="">Select Stream</option>${optionsHtml(['Mathematics','Biology','Arts','Commerce'],r.Stream)}</select></div><div class="field"><label>IT Subject in Place of This Language</label><select id="eIT">${optionsHtml(configCache.itReplacement,r['IT Subject in Place of This Language'])}</select></div><div class="field"><label>Additional Subject / Language Status</label><select id="eAdditional">${optionsHtml(configCache.additionalSubjects,r['Additional Subject'])}</select></div></div>`;}
function setEditClass(){const c=$('eClass').value;$('eJob').value=['9th','10th'].includes(c)?'Domestic Data Entry Operator':'Web Developer';$('eStreamWrap').style.display=['11th','12th'].includes(c)?'':'none';$('eStream').required=['11th','12th'].includes(c);}
function modal(title,body,buttons=''){const old=$('modal');if(old)old.remove();document.body.insertAdjacentHTML('beforeend',`<div id="modal" class="modal"><div class="modal-card"><div class="modal-head"><h2>${title}</h2><button class="mini" onclick="closeModal()">✕</button></div><div>${body}</div>${buttons?`<div class="modal-actions">${buttons}</div>`:''}</div></div>`);}
function closeModal(){$('modal')?.remove();}
function findRow(row){return records.find(x=>Number(x._row)===Number(row));}
function viewStudent(row){const r=findRow(row);if(!r)return;const fields=['Academic Year','Class','Section','Roll Number','Student Name',"Father's Name",'Medium','Gender','Mobile Number','Samagra ID','Trade','Job Role','Stream','IT Subject in Place of This Language','Additional Subject'];modal('Student Details','<div class="detail-grid">'+fields.map(k=>`<div><small>${esc(k)}</small><b>${esc(r[k]||'—')}</b></div>`).join('')+'</div>','<button class="btn secondary" onclick="closeModal()">Close</button>');}
function editStudent(row){const r=findRow(row);if(!r)return;modal('Edit Student',editForm(r),'<button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveEdit('+row+')">Save Changes</button>');$('eClass').value=r.Class;$('eGender').value=r.Gender;$('eClass').addEventListener('change',setEditClass);setEditClass();}
async function saveEdit(row){const d={'Academic Year':$('eYear').value,Class:$('eClass').value,Section:$('eSection').value,'Roll Number':$('eRoll').value.trim(),'Student Name':$('eName').value.trim(),"Father's Name":$('eFather').value.trim(),Medium:$('eMedium').value,Gender:$('eGender').value,'Mobile Number':$('eMobile').value.trim(),'Samagra ID':$('eSamagra').value.trim(),Trade:'IT-ITeS','Job Role':$('eJob').value,Stream:['11th','12th'].includes($('eClass').value)?$('eStream').value:'','IT Subject in Place of This Language':$('eIT').value,'Additional Subject':$('eAdditional').value};try{await API.updateStudent(adminPin,row,d);closeModal();msg('Student updated successfully.','success');await applyFilters();}catch(e){msg(e.message,'error');}}
async function deleteStudent(row){const r=findRow(row);if(!r)return;if(!confirm(`Delete ${r['Student Name']}? This record will move to Deleted Records.`))return;try{await API.deleteStudent(adminPin,row);msg('Student deleted.','success');await applyFilters();await loadDeleted();}catch(e){msg(e.message,'error');}}
async function loadDeleted(){const d=await API.getDeleted(adminPin);$('deletedRows').innerHTML=d.length?d.map(x=>`<tr><td>${esc(x.deletedAt)}</td><td>${esc(x.type)}</td><td><button class="mini" onclick="restoreRecord(${x.row})">Restore</button></td></tr>`).join(''):'<tr><td colspan="3">No deleted records.</td></tr>';}
async function restoreRecord(row){if(!confirm('Restore this student record?'))return;try{await API.restoreDeleted(adminPin,row);msg('Record restored.','success');await refreshAll();await loadDeleted();}catch(e){msg(e.message,'error');}}
function csvEscape(v){return '"'+String(v??'').replace(/"/g,'""')+'"';}
function exportCSV(){const cols=['Academic Year','Class','Section','Roll Number','Student Name',"Father's Name",'Medium','Gender','Mobile Number','Samagra ID','Trade','Job Role','Stream','IT Subject in Place of This Language','Additional Subject'];const csv=[cols,...records.map(r=>cols.map(c=>r[c]||''))].map(row=>row.map(csvEscape).join(',')).join('\r\n');downloadBlob(csv,'vocational-student-records.csv','text/csv;charset=utf-8');}
function exportExcel(){const cols=['Sr. No.','Academic Year','Class','Section','Roll Number','Student Name',"Father's Name",'Medium','Gender','Mobile Number','Samagra ID','Trade','Job Role','Stream','IT Subject in Place of This Language','Additional Subject'];const rows=records.map((r,i)=>[i+1,...cols.slice(1).map(c=>r[c]||'')]);const html='<html><head><meta charset="UTF-8"></head><body><table border="1"><tr>'+cols.map(c=>`<th>${esc(c)}</th>`).join('')+'</tr>'+rows.map(row=>'<tr>'+row.map(c=>`<td>${esc(c)}</td>`).join('')+'</tr>').join('')+'</table></body></html>';downloadBlob(html,'vocational-student-records.xls','application/vnd.ms-excel');}
function downloadBlob(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function printReport(){const w=window.open('','_blank');w.document.write('<html><head><title>Vocational Student Report</title><style>body{font-family:Arial}table{border-collapse:collapse;width:100%;font-size:11px}th,td{border:1px solid #777;padding:5px}th{background:#eee}</style></head><body><h2>Vocational Student Record Report</h2><table><tr>'+['Sr. No.','Academic Year','Class','Section','Roll Number','Student Name',"Father's Name",'Medium','Gender','Mobile Number','Samagra ID','Trade','Job Role','Stream','IT Subject in Place of This Language','Additional Subject'].map(c=>`<th>${esc(c)}</th>`).join('')+'</tr>'+records.map((r,i)=>'<tr>'+[i+1,'Academic Year','Class','Section','Roll Number','Student Name',"Father's Name",'Medium','Gender','Mobile Number','Samagra ID','Trade','Job Role','Stream','IT Subject in Place of This Language','Additional Subject'].map((c,j)=>`<td>${esc(j===0?i+1:r[c]||'—')}</td>`).join('')+'</tr>').join('')+'</table><script>window.print();</script></body></html>');w.document.close();}
function fieldRow(f,i){return `<div class="builder-row" data-index="${i}"><input class="sf-name" value="${esc(f.field)}" ${f.system?'readonly':''}><select class="sf-type"><option value="text" ${f.type==='text'?'selected':''}>text</option><option value="dropdown" ${f.type==='dropdown'?'selected':''}>dropdown</option><option value="tel" ${f.type==='tel'?'selected':''}>tel</option><option value="number" ${f.type==='number'?'selected':''}>number</option></select><input class="sf-options" placeholder="Options separated by |" value="${esc(f.options)}"><select class="sf-required"><option value="Yes" ${f.required?'selected':''}>Required</option><option value="No" ${!f.required?'selected':''}>Optional</option></select><input class="sf-classes" placeholder="All or 9th|10th" value="${esc(f.onlyClasses||'All')}"><input class="sf-section" placeholder="Section" value="${esc(f.section||'Custom')}"><label><input class="sf-enabled" type="checkbox" ${f.enabled?'checked':''}> On</label><button class="mini danger" onclick="removeField(${i})">Delete</button></div>`;}
function renderBuilder(){$('builder').innerHTML=settingsCache.map(fieldRow).join('');}
async function loadSettings(){settingsCache=await API.getSettings();renderBuilder();}
async function loadConfig(){configCache=await API.getConfig();$('fYear').innerHTML='<option value="">All Academic Years</option>'+optionsHtml(configCache.academicYears);$('fSection').innerHTML='<option value="">All Sections</option>'+optionsHtml(configCache.sections);}
function addField(){settingsCache.push({field:'New Custom Field',type:'text',options:'',required:false,enabled:true,onlyClasses:'All',system:false,section:'Custom'});renderBuilder();}
function removeField(i){if(settingsCache[i].system)return alert('Core field cannot be deleted.');settingsCache.splice(i,1);renderBuilder();}
async function saveSettings(){const rows=[...document.querySelectorAll('.builder-row')];const next=rows.map((r,i)=>({...settingsCache[i],field:r.querySelector('.sf-name').value.trim(),type:r.querySelector('.sf-type').value,options:r.querySelector('.sf-options').value,required:r.querySelector('.sf-required').value==='Yes',onlyClasses:r.querySelector('.sf-classes').value||'All',section:r.querySelector('.sf-section').value||'Custom',enabled:r.querySelector('.sf-enabled').checked}));try{settingsCache=await API.saveSettings(adminPin,next);renderBuilder();msg('Form Builder saved.','success');}catch(e){msg(e.message,'error');}}
async function saveConfig(){const cfg={academicYears:$('cfgYears').value.split(/[,\n|]+/).map(x=>x.trim()).filter(Boolean),sections:$('cfgSections').value.split(/[,\n|]+/).map(x=>x.trim()).filter(Boolean),itReplacement:configCache.itReplacement,additionalSubjects:configCache.additionalSubjects};try{configCache=await API.saveConfig(adminPin,cfg);await loadConfig();msg('Academic years and sections saved.','success');}catch(e){msg(e.message,'error');}}

/* Admission Test admin center — uses the existing Google Sheet/API only. */
let admissionTestsCache=[];
let admissionCandidatesCache=[];
function admissionEsc(v){return esc(v);}
async function loadAdmissionCenter(){
  try{
    const tests=await API.getAdmissionTests(adminPin)||[];
    admissionTestsCache=tests;
    const rows=$('admissionTestRows');
    if(rows) rows.innerHTML=tests.length?tests.map(t=>`<tr><td>${admissionEsc(t['Test ID'])}</td><td>${admissionEsc(t['Academic Year'])}</td><td>${admissionEsc(t.Class)}</td><td>${admissionEsc(t.Trade)}</td><td>${admissionEsc(t['Job Role'])}</td><td>${admissionEsc(t['Test Date'])}</td><td>${admissionEsc(t['Total Seats'])}</td><td>${admissionEsc(t['Max Marks'])}</td><td>${admissionEsc(t.Status)}</td><td><button class="mini" onclick="openAdmissionQuestions('${admissionEsc(t['Test ID'])}')">Questions</button> <button class="mini danger" onclick="deleteAdmissionTest('${admissionEsc(t['Test ID'])}')">Delete</button></td></tr>`).join(''):'<tr><td colspan="10">No admission tests found.</td></tr>';
    const sel=$('admissionTestSelect');
    if(sel){const old=sel.value;sel.innerHTML='<option value="">Select Admission Test</option>'+tests.map(t=>`<option value="${admissionEsc(t['Test ID'])}">${admissionEsc(t.Class)} • ${admissionEsc(t.Trade)} • ${admissionEsc(t['Test ID'])}</option>`).join('');if(tests.some(t=>t['Test ID']===old))sel.value=old;}
    if($('admissionTestSelect')?.value) await loadAdmissionCandidates();
    else { $('admissionCandidateRows').innerHTML='<tr><td colspan="11">Select an admission test.</td></tr>'; $('admissionMeritRows').innerHTML=''; }
    await refreshAdmissionMerit();
  }catch(e){msg(e.message||'Admission tests could not be loaded.','error');}
}
function openAdmissionTestForm(){
  modal('Create Admission Test',`<div class="grid edit-grid"><div class="field"><label>Academic Year</label><input id="adYear" value="2026-27"></div><div class="field"><label>Class</label><select id="adClass"><option>9th</option><option>10th</option><option>11th</option><option>12th</option></select></div><div class="field"><label>Trade</label><select id="adTrade"><option>IT-ITeS</option><option>Agriculture</option></select></div><div class="field"><label>Job Role</label><input id="adJob" value="Domestic Data Entry Operator"></div><div class="field"><label>Test Date</label><input id="adDate" type="date"></div><div class="field"><label>Total Seats</label><input id="adSeatsInput" type="number" min="0" value="30"></div><div class="field"><label>Max Marks</label><input id="adMax" type="number" min="1" value="100"></div><div class="field"><label>Status</label><select id="adStatus"><option>Open</option><option>Closed</option></select></div><div class="field"><label>Notes</label><input id="adNotes"></div></div>`,`<button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveAdmissionTestAdmin()">Save Test</button>`);
}
async function saveAdmissionTestAdmin(){try{const d={academicYear:$('adYear').value,class:$('adClass').value,trade:$('adTrade').value,jobRole:$('adJob').value,testDate:$('adDate').value,totalSeats:$('adSeatsInput').value,maxMarks:$('adMax').value,status:$('adStatus').value,notes:$('adNotes').value};await API.saveAdmissionTest(adminPin,d);closeModal();msg('Admission test saved successfully.','success');await loadAdmissionCenter();}catch(e){msg(e.message||'Could not save admission test.','error');}}
async function deleteAdmissionTest(id){if(!confirm('Delete this admission test and its candidates/questions?'))return;try{await API.deleteAdmissionTest(adminPin,id);msg('Admission test deleted.','success');await loadAdmissionCenter();}catch(e){msg(e.message||'Could not delete admission test.','error');}}
async function loadAdmissionCandidates(){const tid=$('admissionTestSelect')?.value;if(!tid)return;try{const a=await API.getAdmissionCandidates(adminPin,tid)||[];admissionCandidatesCache=a;const q=($('admissionSearch')?.value||'').toLowerCase();const rows=$('admissionCandidateRows');const filtered=a.filter(x=>[x['Application No'],x['Roll Number'],x['Student Name']].join(' ').toLowerCase().includes(q));rows.innerHTML=filtered.length?filtered.map(x=>`<tr><td>${admissionEsc(x.Rank||'')}</td><td>${admissionEsc(x['Application No'])}</td><td>${admissionEsc(x['Roll Number'])}</td><td>${admissionEsc(x['Student Name'])}</td><td>${admissionEsc(x["Father's Name"])}</td><td>${admissionEsc(x.Trade)}</td><td>${admissionEsc(x['Job Role'])}</td><td>${admissionEsc(x.Marks)}</td><td>${admissionEsc(x.Percentage)}</td><td>${admissionEsc(x.Status)}</td><td><button class="mini danger" onclick="deleteAdmissionCandidate('${admissionEsc(x['Candidate ID'])}')">Delete</button></td></tr>`).join(''):'<tr><td colspan="11">No candidates found.</td></tr>';await refreshAdmissionMerit();}catch(e){msg(e.message||'Candidates could not be loaded.','error');}}
function openAdmissionCandidateForm(){const tid=$('admissionTestSelect')?.value;if(!tid)return msg('Please select an admission test first.','error');const t=admissionTestsCache.find(x=>x['Test ID']===tid)||{};modal('Add Admission Candidate',`<div class="grid edit-grid"><div class="field"><label>Application No.</label><input id="acApp"></div><div class="field"><label>Student Name</label><input id="acName"></div><div class="field"><label>Father's Name</label><input id="acFather"></div><div class="field"><label>Roll Number</label><input id="acRoll"></div><div class="field"><label>Mobile</label><input id="acMobile" maxlength="10"></div><div class="field"><label>Marks / ${admissionEsc(t['Max Marks']||100)}</label><input id="acMarks" type="number" min="0"></div><div class="field"><label>Tie Breaker</label><input id="acTie" type="number" value="0"></div><div class="field"><label>Notes</label><input id="acNotes"></div></div>`,`<button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveAdmissionCandidateAdmin()">Save Candidate</button>`);}
async function saveAdmissionCandidateAdmin(){try{await API.saveAdmissionCandidate(adminPin,{testId:$('admissionTestSelect').value,applicationNo:$('acApp').value.trim(),studentName:$('acName').value.trim(),fatherName:$('acFather').value.trim(),rollNumber:$('acRoll').value.trim(),mobile:$('acMobile').value.trim(),marks:$('acMarks').value,tieBreaker:$('acTie').value,notes:$('acNotes').value});closeModal();msg('Candidate saved successfully.','success');await loadAdmissionCandidates();}catch(e){msg(e.message||'Could not save candidate.','error');}}
async function deleteAdmissionCandidate(id){if(!confirm('Delete this candidate?'))return;try{await API.deleteAdmissionCandidate(adminPin,id);msg('Candidate deleted.','success');await loadAdmissionCandidates();}catch(e){msg(e.message||'Could not delete candidate.','error');}}
async function refreshAdmissionMerit(){const tid=$('admissionTestSelect')?.value;if(!tid)return;try{const r=await API.getAdmissionMerit(adminPin,tid)||{};const merit=r.merit||[];const body=$('admissionMeritRows');if(body)body.innerHTML=merit.length?merit.map(x=>`<tr><td>${admissionEsc(x.rank||x.Rank||'')}</td><td>${admissionEsc(x.applicationNo||x['Application No'])}</td><td>${admissionEsc(x.rollNumber||x['Roll Number'])}</td><td>${admissionEsc(x.studentName||x['Student Name'])}</td><td>${admissionEsc(x.fatherName||x["Father's Name"])}</td><td>${admissionEsc(x.marks||x.Marks)}</td><td>${admissionEsc(x.maxMarks||x['Max Marks'])}</td><td>${admissionEsc(x.percentage||x.Percentage)}</td><td>${admissionEsc(x.status||x.Status)}</td></tr>`).join(''):'<tr><td colspan="9">No merit records.</td></tr>';const st=r.stats||{};['adTotal','adSeats','adSelected','adWaiting','adVacant'].forEach((id,i)=>{if($(id))$(id).textContent=[st.totalApplicants||0,st.totalSeats||0,st.selected||0,st.waiting||0,st.vacantSeats||0][i];});}catch(e){msg(e.message||'Merit could not be loaded.','error');}}
function downloadAdmissionCSV(){const tid=$('admissionTestSelect')?.value;if(!tid||!admissionCandidatesCache.length)return msg('Select a test with candidates first.','error');const cols=['Rank','Application No','Roll Number','Student Name',"Father's Name",'Marks','Max Marks','Percentage','Status'];const csv='\\ufeff'+[cols,...admissionCandidatesCache.map(x=>cols.map(c=>x[c]||''))].map(r=>r.map(csvEscape).join(',')).join('\\r\\n');downloadBlob(csv,'admission-merit.csv','text/csv;charset=utf-8');}
function printAdmissionMerit(){const area=$('admissionPrintArea');if(!area)return;const w=window.open('','_blank');w.document.write('<html><head><title>Admission Merit List</title><style>body{font-family:Arial;padding:20px}table{border-collapse:collapse;width:100%;font-size:12px}th,td{border:1px solid #777;padding:6px}th{background:#eee}</style></head><body><h2>Admission Merit List</h2>'+area.outerHTML+'<script>window.print();<\\/script></body></html>');w.document.close();}
async function openAdmissionQuestions(testId){try{const q=await API.getAdmissionQuestions(adminPin,testId)||[];modal('Admission Questions',`<div class="toolbar"><button class="btn primary" onclick="openAdmissionQuestionForm('${admissionEsc(testId)}')">+ Add Question</button></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>No.</th><th>Question</th><th>Correct</th><th>Marks</th><th>Action</th></tr></thead><tbody>${q.length?q.map(x=>`<tr><td>${admissionEsc(x['Question No'])}</td><td>${admissionEsc(x.Question)}</td><td>${admissionEsc(['A','B','C','D'][Number(x.Correct)||0])}</td><td>${admissionEsc(x.Marks)}</td><td><button class="mini danger" onclick="deleteAdmissionQuestion('${admissionEsc(x['Question ID'])}','${admissionEsc(testId)}')">Delete</button></td></tr>`).join(''):'<tr><td colspan="5">No questions yet.</td></tr>'}</tbody></table></div>`);}catch(e){msg(e.message||'Questions could not be loaded.','error');}}
function openAdmissionQuestionForm(testId){modal('Add Admission Question',`<div class="grid edit-grid"><div class="field"><label>Question No.</label><input id="aqNo" type="number" value="1"></div><div class="field"><label>Marks</label><input id="aqMarks" type="number" value="1" min="1"></div><div class="field"><label>Question</label><textarea id="aqQ"></textarea></div><div class="field"><label>Option A</label><input id="aqA"></div><div class="field"><label>Option B</label><input id="aqB"></div><div class="field"><label>Option C</label><input id="aqC"></div><div class="field"><label>Option D</label><input id="aqD"></div><div class="field"><label>Correct Option</label><select id="aqCorrect"><option value="0">A</option><option value="1">B</option><option value="2">C</option><option value="3">D</option></select></div></div>`,`<button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveAdmissionQuestionAdmin('${admissionEsc(testId)}')">Save Question</button>`);}
async function saveAdmissionQuestionAdmin(testId){try{await API.saveAdmissionQuestion(adminPin,{testId,questionNo:$('aqNo').value,question:$('aqQ').value,optionA:$('aqA').value,optionB:$('aqB').value,optionC:$('aqC').value,optionD:$('aqD').value,correct:$('aqCorrect').value,marks:$('aqMarks').value});closeModal();msg('Question saved successfully.','success');await openAdmissionQuestions(testId);await loadAdmissionCenter();}catch(e){msg(e.message||'Question could not be saved.','error');}}
async function deleteAdmissionQuestion(id,testId){if(!confirm('Delete this question?'))return;try{await API.deleteAdmissionQuestion(adminPin,id);await openAdmissionQuestions(testId);await loadAdmissionCenter();}catch(e){msg(e.message||'Question could not be deleted.','error');}}
function showTab(tab){if(tab==='admission' && typeof loadAdmissionCenter==='function') loadAdmissionCenter();document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('hidden',x.id!=='panel-'+tab));if(tab==='deleted')loadDeleted();if(tab==='settings'){loadSettings();$('cfgYears').value=(configCache.academicYears||[]).join(', ');$('cfgSections').value=(configCache.sections||[]).join(', ');}}
function saveApiUrl(){const v=$('apiUrl').value.trim();localStorage.setItem('sandipani_api_url',v);msg('API URL saved in this browser. For all users, update js/config.js too.','success');}
async function setupInfo(){try{const d=await API.call('setup');$('setupInfo').innerHTML='<b>Google Sheet:</b> <a target="_blank" href="'+esc(d.sheetUrl)+'">Open Sheet</a>'; }catch(e){$('setupInfo').textContent=e.message;}}
document.addEventListener('DOMContentLoaded',()=>{$('adminPin')?.addEventListener('keydown',e=>{if(e.key==='Enter')adminLogin();});$('apiUrl').value=localStorage.getItem('sandipani_api_url')||DEFAULT_API_URL;});

async function loadGalleryAdmin(){
  const rows=await API.getGallery();
  const labels={guest:'Guest Lectures',industrial:'Industrial Visit',classroom:'Class Room Teaching',activities:'Student Activities'};
  const box=$('galleryAdminRows'); if(!box)return;
  box.innerHTML=(rows||[]).map(x=>`<tr><td>${esc(labels[x.section]||x.section)}</td><td>${esc(x.title)}</td><td><img src="${esc(x.thumbnailUrl||x.url)}" style="width:90px;height:60px;object-fit:cover;border-radius:8px"></td><td><button class="mini danger" onclick="deleteGalleryPhoto('${esc(x.id)}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="4">No uploaded photos yet.</td></tr>';
}
async function uploadGalleryPhoto(){
  const file=$('galleryFile')?.files?.[0], section=$('gallerySection')?.value, title=$('galleryTitle')?.value.trim(), status=$('galleryUploadStatus');
  if(!file)return msg('Select a photo first.','error');
  if(!title)return msg('Enter a photo title.','error');
  if(!['image/jpeg','image/png','image/webp'].includes(file.type))return msg('Only JPG, PNG or WebP images are allowed.','error');
  status.textContent='Preparing photo…';status.className='message';status.style.display='block';
  try{
    const prepared=await prepareGalleryImage_(file);
    await API.uploadGallery(adminPin,{section,title,name:prepared.name,mimeType:prepared.mimeType,base64:prepared.base64});
    status.textContent='Photo uploaded successfully.';status.className='message success';
    $('galleryFile').value='';$('galleryTitle').value='';await loadGalleryAdmin();
  }catch(e){status.textContent=e.message||'Photo upload failed.';status.className='message error';}
}
function prepareGalleryImage_(file){
  return new Promise((resolve,reject)=>{
    const img=new Image(), url=URL.createObjectURL(file);
    img.onload=()=>{
      try{
        const maxSide=1800, scale=Math.min(1,maxSide/Math.max(img.naturalWidth,img.naturalHeight));
        const w=Math.max(1,Math.round(img.naturalWidth*scale)), h=Math.max(1,Math.round(img.naturalHeight*scale));
        const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;
        canvas.getContext('2d').drawImage(img,0,0,w,h);
        const make=q=>{
          const dataUrl=canvas.toDataURL('image/jpeg',q), b64=dataUrl.split(',')[1]||'';
          if(b64.length<=2200000 || q<=0.55){
            URL.revokeObjectURL(url);
            resolve({name:(file.name.replace(/\.[^.]+$/,'')||'gallery')+'.jpg',mimeType:'image/jpeg',base64:b64});
          }else make(q-0.08);
        };
        make(0.82);
      }catch(err){URL.revokeObjectURL(url);reject(err);}
    };
    img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Could not read the selected image.'));};
    img.src=url;
  });
}
async function deleteGalleryPhoto(id){if(!confirm('Delete this gallery photo?'))return;try{await API.deleteGallery(adminPin,id);msg('Gallery photo deleted.','success');await loadGalleryAdmin();}catch(e){msg(e.message,'error');}}
