const CORE_NAMES=['Academic Year','Class','Section','Roll Number','Student Name',"Father's Name",'Medium','Gender','Mobile Number','Samagra ID','Trade','Job Role','Stream','IT Subject Opted in Place of This Language','Additional Subject'];
let FORM_SETTINGS=[], APP_CONFIG={};
const $=id=>document.getElementById(id);
function escR(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function opts(v){return String(v||'').split('|').map(x=>x.trim()).filter(Boolean);}
function fieldHtml(f){let input='';const id='fld_'+btoa(unescape(encodeURIComponent(f.field))).replace(/[^a-zA-Z0-9]/g,'_');if(f.field==='Trade')input='<input name="Trade" value="IT-ITeS" readonly class="locked">';else if(f.field==='Job Role')input='<input name="Job Role" readonly class="locked" id="jobRole">';else if(f.field==='Stream')input='<select name="Stream" id="stream"><option value="">Select Stream</option>'+opts(f.options).map(x=>`<option>${escR(x)}</option>`).join('')+'</select>';else if(f.type==='dropdown')input='<select name="'+escR(f.field)+'" id="'+id+'"><option value="">Select '+escR(f.field)+'</option>'+opts(f.options).map(x=>`<option>${escR(x)}</option>`).join('')+'</select>';else input='<input name="'+escR(f.field)+'" id="'+id+'" type="'+(f.type==='tel'?'tel':f.type==='number'?'number':'text')+'">';return `<div class="field" data-field="${escR(f.field)}"><label>${escR(f.field)}${f.required?' <span class="req">*</span>':''}</label>${input}</div>`;}
function render(){const box=$('dynamicForm');box.innerHTML='';const groups={};FORM_SETTINGS.filter(f=>f.enabled).forEach(f=>(groups[f.section||'General']??=[]).push(f));Object.entries(groups).forEach(([section,fields])=>{const s=document.createElement('div');s.className='section';s.textContent=section;box.appendChild(s);const g=document.createElement('div');g.className='grid';fields.forEach(f=>{const temp=document.createElement('div');temp.innerHTML=fieldHtml(f);const wrap=temp.firstElementChild;if(f.type==='textarea')wrap.classList.add('full');g.appendChild(wrap);});box.appendChild(g);});
  const cls=$('dynamicForm').querySelector('[name="Class"]'); if(cls) cls.addEventListener('change',updateConditional); updateConditional();
  const roll=$('dynamicForm').querySelector('[name="Roll Number"]'); if(roll){roll.inputMode='numeric';roll.maxLength=6;roll.addEventListener('input',()=>roll.value=roll.value.replace(/\D/g,'').slice(0,6));}
  const mobile=$('dynamicForm').querySelector('[name="Mobile Number"]'); if(mobile){mobile.inputMode='numeric';mobile.maxLength=10;mobile.pattern='[6-9][0-9]{9}';mobile.addEventListener('input',()=>mobile.value=mobile.value.replace(/\D/g,'').slice(0,10));}
  const sam=$('dynamicForm').querySelector('[name="Samagra ID"]'); if(sam){sam.inputMode='numeric';sam.maxLength=9;sam.pattern='[0-9]{9}';sam.addEventListener('input',()=>sam.value=sam.value.replace(/\D/g,'').slice(0,9));}
}
function updateConditional(){const cls=$('dynamicForm').querySelector('[name="Class"]')?.value||'';const job=$('dynamicForm').querySelector('[name="Job Role"]');if(job)job.value=(cls==='9th'||cls==='10th')?'Domestic Data Entry Operator':(cls==='11th'||cls==='12th')?'Web Developer':'';const streamWrap=$('dynamicForm').querySelector('[data-field="Stream"]');if(streamWrap)streamWrap.style.display=(cls==='11th'||cls==='12th')?'':'none';const stream=$('dynamicForm').querySelector('[name="Stream"]');if(stream)stream.required=cls==='11th'||cls==='12th';}
function collect(){const data={};$('registrationForm').querySelectorAll('[name]').forEach(el=>{if(el.closest('[data-field]')?.style.display!=='none')data[el.name]=el.value.trim();});data.Trade='IT-ITeS';data['Job Role']=$('dynamicForm').querySelector('[name="Job Role"]')?.value||'';if(['9th','10th'].includes(data.Class))data.Stream='';return data;}
function validate(data){for(const k of ['Academic Year','Class','Section','Student Name',"Father's Name",'Medium','Gender','Mobile Number','Samagra ID','IT Subject Opted in Place of This Language','Additional Subject'])if(!data[k])throw new Error(k+' is required.');if(['11th','12th'].includes(data.Class)&&!data.Stream)throw new Error('Stream is required for '+data.Class+'.');if(!/^[6-9]\d{9}$/.test(data['Mobile Number']))throw new Error('Enter a valid 10-digit Indian mobile number.');if(!/^\d{9}$/.test(data['Samagra ID']))throw new Error('Samagra ID must be exactly 9 digits.');}
async function init(){try{[FORM_SETTINGS,APP_CONFIG]=await Promise.all([API.getSettings(),API.getConfig()]);if(!FORM_SETTINGS.some(f=>f.field==='Roll Number'))FORM_SETTINGS.splice(3,0,{field:'Roll Number',type:'text',options:'',required:false,enabled:true,onlyClasses:'All',system:true,section:'Student Information'});render();}catch(e){$('dynamicForm').innerHTML='<div class="notice">Unable to load form: '+escR(e.message)+'</div>';}}
async function submit(e){e.preventDefault();const btn=$('submitBtn');try{const data=collect();validate(data);btn.disabled=true;btn.textContent='Saving…';await API.registerStudent(data);$('registrationForm').reset();render();showMsg('Student record saved successfully to Google Sheet.','success');}catch(err){showMsg(err.message,'error');}finally{btn.disabled=false;btn.textContent='Save Student Record';}}
function showMsg(t,type){const m=$('message');m.textContent=t;m.className='message '+type;m.style.display='block';window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'});}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-school-name]').forEach(e=>e.textContent=SCHOOL_CONFIG.name);$('registrationForm').addEventListener('submit',submit);init();});
